Mystic-Type: GameState Class Reference
GameState Class Reference
Client-side container for the latest world state.
#include <Network/Client/GameState.hpp>
Public Member Functions
void upsertPlayer (int id, uint8_t x, uint8_t y, uint8_t hp, uint16_t score)
Insert or update a player entry.
void upsertBullet (int id, uint8_t x, uint8_t y, int8_t vx, int8_t vy)
Insert or update a bullet entry.
void upsertMonster (int id, uint8_t x, uint8_t y, uint8_t hp, uint8_t type)
Insert or update a monster entry.
void clear ()
Clear all cached entities.
void clearPlayers ()
Clear only player entries.
std::vector< PlayerState > listPlayers () const
Return a snapshot list of current players.
std::vector< BulletState > listBullets () const
Return a snapshot list of current bullets.
std::vector< MonsterState > listMonsters () const
Return a snapshot list of current monsters.
Private Attributes
std::unordered_map< int, PlayerState > _players
std::unordered_map< int, BulletState > _bullets
std::unordered_map< int, MonsterState > _monsters
Detailed Description
Client-side container for the latest world state.
Definition at line 50 of file GameState.hpp.
Member Function Documentation
clear()
void GameState::clear () inline
Clear all cached entities.
Definition at line 79 of file GameState.hpp.
References _bullets, _monsters, and _players.
Referenced by GraphicClient::processNetworkEvents(), and GraphicClient::run().
clearPlayers()
void GameState::clearPlayers () inline
Clear only player entries.
Definition at line 89 of file GameState.hpp.
References _players.
Referenced by GraphicClient::processNetworkEvents().
listBullets()
std::vector< BulletState > GameState::listBullets () const inline
Return a snapshot list of current bullets.
Definition at line 109 of file GameState.hpp.
References _bullets.
listMonsters()
std::vector< MonsterState > GameState::listMonsters () const inline
Return a snapshot list of current monsters.
Definition at line 121 of file GameState.hpp.
References _monsters.
listPlayers()
std::vector< PlayerState > GameState::listPlayers () const inline
Return a snapshot list of current players.
Definition at line 97 of file GameState.hpp.
References _players.
Referenced by GraphicClient::init(), GraphicClient::processNetworkEvents(), GraphicClient::render(), and GraphicClient::updateEntities().
upsertBullet()
void GameState::upsertBullet (int id, uint8_t x, uint8_t y, int8_t vx, int8_t vy) inline
Insert or update a bullet entry.
Definition at line 63 of file GameState.hpp.
References _bullets.
upsertMonster()
void GameState::upsertMonster (int id, uint8_t x, uint8_t y, uint8_t hp, uint8_t type) inline
Insert or update a monster entry.
Definition at line 71 of file GameState.hpp.
References _monsters.
Referenced by GraphicClient::processNetworkEvents().
upsertPlayer()
void GameState::upsertPlayer (int id, uint8_t x, uint8_t y, uint8_t hp, uint16_t score) inline
Insert or update a player entry.
Definition at line 55 of file GameState.hpp.
References _players.
Referenced by GraphicClient::init(), and GraphicClient::processNetworkEvents().
Member Data Documentation
_bullets
std::unordered_map<int, BulletState> GameState::_bullets private
Definition at line 132 of file GameState.hpp.
Referenced by clear(), listBullets(), and upsertBullet().
_monsters
std::unordered_map<int, MonsterState> GameState::_monsters private
Definition at line 133 of file GameState.hpp.
Referenced by clear(), listMonsters(), and upsertMonster().
_players
std::unordered_map<int, PlayerState> GameState::_players private
Definition at line 131 of file GameState.hpp.
Referenced by clear(), clearPlayers(), listPlayers(), and upsertPlayer().
The documentation for this class was generated from the following file:
Network/Client/GameState.hpp