Mystic-Type: TCPServer Class Reference
TCPServer Class Reference
Simple TCP server handling client connections and lobby state.
#include <Network/TransportLayer/TCP/TCPServer.hpp>
Classes
struct Client
Lightweight representation of a connected client.
struct LobbyInfo
Public Member Functions
TCPServer (uint16_t port, SessionManager &sessions, ChildProcessManager *childMgr=nullptr)
Construct a new TCPServer bound to the given port.
~TCPServer ()
Destroy the TCPServer, closing the listening socket.
void run ()
Run the main accept/receive loop (blocking).
Private Types
enum class RecvResult { Disconnected , Incomplete , Ok }
Result of a receive attempt.
Private Member Functions
void acceptNewClient ()
Accept incoming connection and register a new client slot.
void processClientData (Client &client)
Read and handle data for a single client.
void sendPingToAll ()
Send a ping packet to every connected client.
void checkHeartbeat ()
Disconnect clients whose heartbeat timed out.
long getCurrentTime ()
Get current time in milliseconds.
bool waitForReadable (socket_t fd, int timeoutSec, int timeoutUsec=0)
Block until a file descriptor is readable or times out.
void closeFd (socket_t &fd)
Close and invalidate a file descriptor.
void resetClient (Client &client)
Reset client fields and close its socket.
int pollSockets (fd_set &readfds, int maxFd, struct timeval &timeout)
Poll all sockets using select().
bool sendPacket (socket_t fd, const Packet &packet)
Send a packet to a specific client fd.
RecvResult receivePacket (socket_t fd, Packet &packet, std::vector< uint8_t > &buffer)
Receive and parse a packet from a client socket.
Packet makeStringPacket (PacketType type, const std::string &payload)
Build a packet carrying a string payload.
Packet makeIdPacket (PacketType type, int value)
Build a packet carrying a simple integer id.
Packet makeLobbyPacket (PacketType type, const std::string &payload)
ssize_t writeFd (socket_t fd, const uint8_t *data, std::size_t size)
Write raw bytes to a socket fd.
ssize_t readFd (socket_t fd, uint8_t *data, std::size_t size)
Read raw bytes from a socket fd.
int selectFdSet (int nfds, fd_set *readfds, fd_set *writefds, fd_set *exceptfds, struct timeval *timeout)
Wrapper around select for testability.
int closeFdRaw (socket_t fd)
Close a raw fd without resetting the caller's variable.
Packet buildPlayerListPacket (const std::string &lobbyCode) const
Build the packet containing the list of connected players.
void sendPlayerListToClient (const Client &client)
Send the current player list to a single client.
void broadcastNewPlayer (const Client &newClient)
Notify all clients of a newly connected player.
bool writeAll (socket_t fd, const uint8_t *data, std::size_t size)
Ensure the full buffer is written to the socket.
bool assignLobby (Client &client, const std::string &code, bool createIfMissing, bool isPublic, bool allowFull=false)
Assign a client to a lobby (public or private).
void removeFromLobby (const Client &client)
Remove a client from its current lobby.
void refreshLobby (const std::string &code)
Resend the player list to all members of a lobby.
std::string autoAssignPublic (Client &client)
Auto-match the client into a public lobby.
std::string generateLobbyCode ()
Generate a random lobby code (6 chars alnum).
void handleLobbyPacket (Client &client, const Packet &packet)
Handle lobby-related packets for a client.
void processIpcMessages ()
void broadcastToLobby (const std::string &lobbyCode, const Packet &packet)
uint16_t allocatePort ()
void ensureLobbyProcess (const std::string &code, bool isPublic)
Private Attributes
Network::TransportLayer::TCPSocket _serverSocket
std::array< Client, MAX_CLIENT > _clients
int _nextId = 1
SessionManager & _sessions
std::unordered_map< std::string, LobbyInfo > _lobbies
std::unordered_map< int, std::string > _clientLobby
ChildProcessManager * _childMgr = nullptr
Detailed Description
Simple TCP server handling client connections and lobby state.
The server accepts new TCP clients, performs a handshake, keeps a small list of connected players, and forwards heartbeat and player list packets to them.
Definition at line 32 of file TCPServer.hpp.
Member Enumeration Documentation
RecvResult
enum class TCPServer::RecvResult strong private
Result of a receive attempt.
Enumerator
Disconnected
Incomplete
Ok
Definition at line 127 of file TCPServer.hpp.
Constructor & Destructor Documentation
TCPServer()
TCPServer::TCPServer (uint16_t port, SessionManager & sessions, ChildProcessManager * childMgr = nullptr)
Construct a new TCPServer bound to the given port.
Parameters
port TCP port to listen on.
Definition at line 39 of file TCPServer.cpp.
References _clients, _serverSocket, Network::TransportLayer::TCPSocket::bindAndListen(), INVALID_SOCKET_FD, and MAX_CLIENT.
~TCPServer()
TCPServer::~TCPServer ()
Destroy the TCPServer, closing the listening socket.
Definition at line 52 of file TCPServer.cpp.
References _clients, _serverSocket, Network::TransportLayer::ASocket::closeSocket(), and resetClient().
Member Function Documentation
acceptNewClient()
void TCPServer::acceptNewClient () private
Accept incoming connection and register a new client slot.
Definition at line 165 of file TCPServer.cpp.
References _clients, _nextId, _serverSocket, _sessions, Network::TransportLayer::TCPSocket::acceptClient(), SessionManager::addSession(), closeFd(), getCurrentTime(), INVALID_SOCKET_FD, makeStringPacket(), REFUSED, sendPacket(), and SERVER_HELLO.
Referenced by run().
allocatePort()
uint16_t TCPServer::allocatePort () private
Definition at line 639 of file TCPServer.cpp.
Referenced by ensureLobbyProcess().
assignLobby()
bool TCPServer::assignLobby (Client & client, const std::string & code, bool createIfMissing, bool isPublic, bool allowFull = false) private
Assign a client to a lobby (public or private).
Definition at line 669 of file TCPServer.cpp.
References _clientLobby, _lobbies, _sessions, ensureLobbyProcess(), TCPServer::Client::id, TCPServer::Client::lobbyCode, MAX_CLIENT, removeFromLobby(), and SessionManager::setLobbyCode().
Referenced by autoAssignPublic(), and handleLobbyPacket().
autoAssignPublic()
std::string TCPServer::autoAssignPublic (Client & client) private
Auto-match the client into a public lobby.
Definition at line 695 of file TCPServer.cpp.
References assignLobby().
broadcastNewPlayer()
void TCPServer::broadcastNewPlayer (const Client & newClient) private
Notify all clients of a newly connected player.
Definition at line 578 of file TCPServer.cpp.
References _clients, TCPServer::Client::hp, TCPServer::Client::id, TCPServer::Client::lobbyCode, NEW_PLAYER, TCPServer::Client::posX, TCPServer::Client::posY, and sendPacket().
Referenced by handleLobbyPacket().
broadcastToLobby()
void TCPServer::broadcastToLobby (const std::string & lobbyCode, const Packet & packet) private
Definition at line 79 of file TCPServer.cpp.
References _clients, INVALID_SOCKET_FD, and sendPacket().
Referenced by checkHeartbeat(), processClientData(), and processIpcMessages().
buildPlayerListPacket()
Packet TCPServer::buildPlayerListPacket (const std::string & lobbyCode) const private
Build the packet containing the list of connected players.
Definition at line 549 of file TCPServer.cpp.
References _clients, and PLAYER_LIST.
Referenced by sendPlayerListToClient().
checkHeartbeat()
void TCPServer::checkHeartbeat () private
Disconnect clients whose heartbeat timed out.
Definition at line 351 of file TCPServer.cpp.
References _clients, broadcastToLobby(), getCurrentTime(), makeStringPacket(), MESSAGE, REFUSED, resetClient(), and sendPacket().
Referenced by run().
closeFd()
void TCPServer::closeFd (socket_t & fd) private
Close and invalidate a file descriptor.
Definition at line 134 of file TCPServer.cpp.
References closeFdRaw(), and INVALID_SOCKET_FD.
Referenced by acceptNewClient(), and resetClient().
closeFdRaw()
int TCPServer::closeFdRaw (socket_t fd) private
Close a raw fd without resetting the caller's variable.
Definition at line 532 of file TCPServer.cpp.
References CLOSE.
Referenced by closeFd().
ensureLobbyProcess()
void TCPServer::ensureLobbyProcess (const std::string & code, bool isPublic) private
Definition at line 647 of file TCPServer.cpp.
References _childMgr, _lobbies, ChildProcessManager::activeCount(), allocatePort(), ChildProcessManager::maxCount(), and ChildProcessManager::spawn().
Referenced by assignLobby().
generateLobbyCode()
std::string TCPServer::generateLobbyCode () private
Generate a random lobby code (6 chars alnum).
Definition at line 605 of file TCPServer.cpp.
References _lobbies.
Referenced by handleLobbyPacket().
getCurrentTime()
long TCPServer::getCurrentTime () private
Get current time in milliseconds.
Definition at line 334 of file TCPServer.cpp.
Referenced by acceptNewClient(), checkHeartbeat(), processClientData(), and run().
handleLobbyPacket()
void TCPServer::handleLobbyPacket (Client & client, const Packet & packet) private
Handle lobby-related packets for a client.
Definition at line 702 of file TCPServer.cpp.
References _lobbies, assignLobby(), broadcastNewPlayer(), CREATE_LOBBY, TCPServer::Client::fd, generateLobbyCode(), TCPServer::Client::handshakeDone, TCPServer::Client::id, JOIN_LOBBY, LOBBY_ERROR, LOBBY_OK, makeLobbyPacket(), MAX_CLIENT, Packet::payload, refreshLobby(), sendPacket(), sendPlayerListToClient(), and Packet::type.
Referenced by processClientData().
makeIdPacket()
Packet TCPServer::makeIdPacket (PacketType type, int value) private
Build a packet carrying a simple integer id.
Definition at line 65 of file TCPServer.cpp.
Referenced by processClientData().
makeLobbyPacket()
Packet TCPServer::makeLobbyPacket (PacketType type, const std::string & payload) private
Definition at line 74 of file TCPServer.cpp.
Referenced by handleLobbyPacket().
makeStringPacket()
Packet TCPServer::makeStringPacket (PacketType type, const std::string & payload) private
Build a packet carrying a string payload.
Definition at line 60 of file TCPServer.cpp.
Referenced by acceptNewClient(), checkHeartbeat(), processClientData(), and processIpcMessages().
pollSockets()
int TCPServer::pollSockets (fd_set & readfds, int maxFd, struct timeval & timeout) private
Poll all sockets using select().
Returns
Number of ready descriptors or -1 on error.
Definition at line 160 of file TCPServer.cpp.
References selectFdSet().
Referenced by run().
processClientData()
void TCPServer::processClientData (Client & client) private
Read and handle data for a single client.
Definition at line 203 of file TCPServer.cpp.
References _clients, _sessions, broadcastToLobby(), CLIENT_HELLO, CREATE_LOBBY, Disconnected, TCPServer::Client::fd, getCurrentTime(), SessionManager::getLobbyCode(), SessionManager::getPseudo(), handleLobbyPacket(), TCPServer::Client::handshakeDone, TCPServer::Client::id, Incomplete, JOIN_LOBBY, TCPServer::Client::lastPongTime, TCPServer::Client::lobbyCode, makeIdPacket(), makeStringPacket(), MESSAGE, OK, Packet::payload, PONG, TCPServer::Client::pseudo, receivePacket(), TCPServer::Client::recvBuffer, REFUSED, resetClient(), sendPacket(), SessionManager::setPseudo(), Packet::type, and SessionManager::updatePong().
Referenced by run().
processIpcMessages()
void TCPServer::processIpcMessages () private
Definition at line 377 of file TCPServer.cpp.
References _childMgr, _clients, _lobbies, broadcastToLobby(), ChildProcessManager::forget(), makeStringPacket(), MESSAGE, removeFromLobby(), and sendPacket().
Referenced by run().
readFd()
ssize_t TCPServer::readFd (socket_t fd, uint8_t * data, std::size_t size) private
Read raw bytes from a socket fd.
Definition at line 522 of file TCPServer.cpp.
Referenced by receivePacket().
receivePacket()
TCPServer::RecvResult TCPServer::receivePacket (socket_t fd, Packet & packet, std::vector< uint8_t > & buffer) private
Receive and parse a packet from a client socket.
Parameters
fd Client socket.
packet Output parsed packet.
buffer Receive buffer for reassembly.
Definition at line 102 of file TCPServer.cpp.
References BUFFER_SIZE, Protocol::consumeChunk(), Disconnected, Protocol::Incomplete, Incomplete, INVALID_SOCKET_FD, Protocol::Ok, Ok, and readFd().
Referenced by processClientData().
refreshLobby()
void TCPServer::refreshLobby (const std::string & code) private
Resend the player list to all members of a lobby.
Definition at line 596 of file TCPServer.cpp.
References _clients, and sendPlayerListToClient().
Referenced by handleLobbyPacket(), and removeFromLobby().
removeFromLobby()
void TCPServer::removeFromLobby (const Client & client) private
Remove a client from its current lobby.
Definition at line 620 of file TCPServer.cpp.
References _clientLobby, _lobbies, _sessions, TCPServer::Client::id, TCPServer::Client::lobbyCode, refreshLobby(), and SessionManager::setLobbyCode().
Referenced by assignLobby(), processIpcMessages(), and resetClient().
resetClient()
void TCPServer::resetClient (Client & client) private
Reset client fields and close its socket.
Definition at line 142 of file TCPServer.cpp.
References _sessions, TCPServer::Client::addr, closeFd(), TCPServer::Client::fd, TCPServer::Client::handshakeDone, TCPServer::Client::handshakeStart, TCPServer::Client::hp, TCPServer::Client::id, TCPServer::Client::lastPongTime, TCPServer::Client::lobbyCode, TCPServer::Client::posX, TCPServer::Client::posY, TCPServer::Client::pseudo, TCPServer::Client::recvBuffer, SessionManager::removeById(), and removeFromLobby().
Referenced by checkHeartbeat(), processClientData(), and ~TCPServer().
run()
void TCPServer::run ()
Run the main accept/receive loop (blocking).
Definition at line 446 of file TCPServer.cpp.
References _clients, _lobbies, _serverSocket, acceptNewClient(), checkHeartbeat(), getCurrentTime(), Network::TransportLayer::ASocket::getSocketFd(), INVALID_SOCKET_FD, pollSockets(), processClientData(), processIpcMessages(), and sendPingToAll().
Referenced by main().
selectFdSet()
int TCPServer::selectFdSet (int nfds, fd_set * readfds, fd_set * writefds, fd_set * exceptfds, struct timeval * timeout) private
Wrapper around select for testability.
Definition at line 527 of file TCPServer.cpp.
Referenced by pollSockets(), and waitForReadable().
sendPacket()
bool TCPServer::sendPacket (socket_t fd, const Packet & packet) private
Send a packet to a specific client fd.
Definition at line 88 of file TCPServer.cpp.
References Protocol::frameTcp(), INVALID_SOCKET_FD, and writeAll().
Referenced by acceptNewClient(), broadcastNewPlayer(), broadcastToLobby(), checkHeartbeat(), handleLobbyPacket(), processClientData(), processIpcMessages(), sendPingToAll(), and sendPlayerListToClient().
sendPingToAll()
void TCPServer::sendPingToAll () private
Send a ping packet to every connected client.
Definition at line 341 of file TCPServer.cpp.
References _clients, PING, and sendPacket().
Referenced by run().
sendPlayerListToClient()
void TCPServer::sendPlayerListToClient (const Client & client) private
Send the current player list to a single client.
Definition at line 572 of file TCPServer.cpp.
References buildPlayerListPacket(), TCPServer::Client::fd, TCPServer::Client::lobbyCode, and sendPacket().
Referenced by handleLobbyPacket(), and refreshLobby().
waitForReadable()
bool TCPServer::waitForReadable (socket_t fd, int timeoutSec, int timeoutUsec = 0) private
Block until a file descriptor is readable or times out.
Definition at line 122 of file TCPServer.cpp.
References selectFdSet().
writeAll()
bool TCPServer::writeAll (socket_t fd, const uint8_t * data, std::size_t size) private
Ensure the full buffer is written to the socket.
Definition at line 537 of file TCPServer.cpp.
References writeFd().
Referenced by sendPacket().
writeFd()
ssize_t TCPServer::writeFd (socket_t fd, const uint8_t * data, std::size_t size) private
Write raw bytes to a socket fd.
Definition at line 517 of file TCPServer.cpp.
Referenced by writeAll().
Member Data Documentation
_childMgr
ChildProcessManager* TCPServer::_childMgr = nullptr private
Definition at line 235 of file TCPServer.hpp.
Referenced by ensureLobbyProcess(), and processIpcMessages().
_clientLobby
std::unordered_map<int, std::string> TCPServer::_clientLobby private
Definition at line 234 of file TCPServer.hpp.
Referenced by assignLobby(), and removeFromLobby().
_clients
std::array<Client, MAX_CLIENT> TCPServer::_clients private
Definition at line 223 of file TCPServer.hpp.
Referenced by acceptNewClient(), broadcastNewPlayer(), broadcastToLobby(), buildPlayerListPacket(), checkHeartbeat(), processClientData(), processIpcMessages(), refreshLobby(), run(), sendPingToAll(), TCPServer(), and ~TCPServer().
_lobbies
std::unordered_map<std::string, LobbyInfo> TCPServer::_lobbies private
Definition at line 233 of file TCPServer.hpp.
Referenced by assignLobby(), ensureLobbyProcess(), generateLobbyCode(), handleLobbyPacket(), processIpcMessages(), removeFromLobby(), and run().
_nextId
int TCPServer::_nextId = 1 private
Definition at line 224 of file TCPServer.hpp.
Referenced by acceptNewClient().
_serverSocket
Network::TransportLayer::TCPSocket TCPServer::_serverSocket private
Definition at line 222 of file TCPServer.hpp.
Referenced by acceptNewClient(), run(), TCPServer(), and ~TCPServer().
_sessions
SessionManager& TCPServer::_sessions private
Definition at line 225 of file TCPServer.hpp.
Referenced by acceptNewClient(), assignLobby(), processClientData(), removeFromLobby(), and resetClient().
The documentation for this class was generated from the following files:
Network/TransportLayer/TCP/TCPServer.hpp
Network/TransportLayer/TCP/TCPServer.cpp