Mystic-Type: ChildProcessManager Class Reference
ChildProcessManager Class Reference
Minimal child process manager to spawn UDP game servers.
#include <server/ChildProcessManager.hpp>
Public Member Functions
ChildProcessManager (std::size_t maxChildren=64)
int spawn (const std::string &lobby, uint16_t udpPort, const std::string &ipcSock)
Spawn a UDP game server process.
std::optional< ChildInfo > get (const std::string &lobby) const
Retrieve info by lobby code.
void forget (const std::string &lobby)
Remove tracking info (does not kill).
std::size_t activeCount () const
std::size_t maxCount () const
Private Attributes
std::unordered_map< std::string, ChildInfo > _children
std::size_t _maxChildren
Detailed Description
Minimal child process manager to spawn UDP game servers.
This is a stub: no restart logic, no signal handling, just spawn and track.
Definition at line 27 of file ChildProcessManager.hpp.
Constructor & Destructor Documentation
ChildProcessManager()
ChildProcessManager::ChildProcessManager (std::size_t maxChildren = 64) inline explicit
Definition at line 29 of file ChildProcessManager.hpp.
Member Function Documentation
activeCount()
std::size_t ChildProcessManager::activeCount () const inline
Definition at line 50 of file ChildProcessManager.hpp.
References _children.
Referenced by TCPServer::ensureLobbyProcess().
forget()
void ChildProcessManager::forget (const std::string & lobby)
Remove tracking info (does not kill).
Definition at line 124 of file ChildProcessManager.cpp.
References _children.
Referenced by TCPServer::processIpcMessages().
get()
std::optional< ChildInfo > ChildProcessManager::get (const std::string & lobby) const
Retrieve info by lobby code.
Definition at line 116 of file ChildProcessManager.cpp.
References _children.
maxCount()
std::size_t ChildProcessManager::maxCount () const inline
Definition at line 51 of file ChildProcessManager.hpp.
References _maxChildren.
Referenced by TCPServer::ensureLobbyProcess().
spawn()
int ChildProcessManager::spawn (const std::string & lobby, uint16_t udpPort, const std::string & ipcSock)
Spawn a UDP game server process.
Parameters
lobby lobby code
udpPort udp port to bind
ipcSock path to IPC socket
Returns
pid on success, -1 on failure
Definition at line 21 of file ChildProcessManager.cpp.
References _children, ChildInfo::ipcSock, ChildInfo::lobbyCode, ChildInfo::pid, and ChildInfo::udpPort.
Referenced by TCPServer::ensureLobbyProcess().
Member Data Documentation
_children
std::unordered_map<std::string, ChildInfo> ChildProcessManager::_children private
Definition at line 54 of file ChildProcessManager.hpp.
Referenced by activeCount(), forget(), get(), and spawn().
_maxChildren
std::size_t ChildProcessManager::_maxChildren private
Definition at line 55 of file ChildProcessManager.hpp.
Referenced by maxCount().
The documentation for this class was generated from the following files:
server/ChildProcessManager.hpp
server/ChildProcessManager.cpp