Mystic-Type: IpcChannel Class Reference
IpcChannel Class Reference
Small IPC helper based on a UNIX datagram socket (SOCK_DGRAM).
#include <server/IpcChannel.hpp>
Public Member Functions
IpcChannel ()=default
~IpcChannel ()
IpcChannel (const IpcChannel &)=delete
IpcChannel & operator= (const IpcChannel &)=delete
bool bindServer (void)
Create a socket and bind to a path (server side).
bool connectClient (const std::string &port)
Create a socket and connect to a path (client side).
bool send (const std::string &msg)
Send a text message (limited to 1024 bytes).
std::optional< std::string > recv (int timeoutMs=0)
Receive a message with optional timeout (ms). timeoutMs = 0 => non-blocking, <0 => blocking, >0 => poll with timeout.
std::string getport (void) const
get ipc port in string format
void close ()
Close the socket and unlink the path when in server mode.
socket_t fd () const
return internal sock fd
Private Attributes
socket_t _sockfd = INVALID_SOCKET_FD
sockaddr_in _addr
bool _isServer = false
Detailed Description
Small IPC helper based on a UNIX datagram socket (SOCK_DGRAM).
Server mode: bind() on a path, then recv/send. Client mode: connect() to the existing path, then recv/send.
Messages are short ASCII strings (<= 1024 bytes); this is not a reliable stream protocol but sufficient for READY/ALLOW/etc control signals.
Definition at line 22 of file IpcChannel.hpp.
Constructor & Destructor Documentation
IpcChannel() [1/2]
IpcChannel::IpcChannel () default
~IpcChannel()
IpcChannel::~IpcChannel ()
Definition at line 17 of file IpcChannel.cpp.
References close().
IpcChannel() [2/2]
IpcChannel::IpcChannel (const IpcChannel &) delete
Member Function Documentation
bindServer()
bool IpcChannel::bindServer (void)
Create a socket and bind to a path (server side).
Returns
true on success.
Definition at line 22 of file IpcChannel.cpp.
References _addr, _isServer, _sockfd, CLOSE, and INVALID_SOCKET_FD.
close()
void IpcChannel::close ()
Close the socket and unlink the path when in server mode.
Definition at line 104 of file IpcChannel.cpp.
References _addr, _isServer, _sockfd, CLOSE, and INVALID_SOCKET_FD.
Referenced by ~IpcChannel().
connectClient()
bool IpcChannel::connectClient (const std::string & port)
Create a socket and connect to a path (client side).
Returns
true on success.
Definition at line 54 of file IpcChannel.cpp.
References _addr, _isServer, _sockfd, CLOSE, and INVALID_SOCKET_FD.
Referenced by main().
fd()
socket_t IpcChannel::fd () const inline
return internal sock fd
Definition at line 69 of file IpcChannel.hpp.
References _sockfd.
getport()
std::string IpcChannel::getport (void) const inline
get ipc port in string format
Definition at line 56 of file IpcChannel.hpp.
References _addr.
operator=()
IpcChannel & IpcChannel::operator= (const IpcChannel &) delete
recv()
std::optional< std::string > IpcChannel::recv (int timeoutMs = 0)
Receive a message with optional timeout (ms). timeoutMs = 0 => non-blocking, <0 => blocking, >0 => poll with timeout.
Definition at line 82 of file IpcChannel.cpp.
References _sockfd, INVALID_SOCKET_FD, and recv().
Referenced by recv().
send()
bool IpcChannel::send (const std::string & msg)
Send a text message (limited to 1024 bytes).
Definition at line 71 of file IpcChannel.cpp.
References _addr, _sockfd, and INVALID_SOCKET_FD.
Referenced by main(), UDPGameServer::run(), and UDPGameServer::updateSimulation().
Member Data Documentation
_addr
sockaddr_in IpcChannel::_addr private
Definition at line 73 of file IpcChannel.hpp.
Referenced by bindServer(), close(), connectClient(), getport(), and send().
_isServer
bool IpcChannel::_isServer = false private
Definition at line 74 of file IpcChannel.hpp.
Referenced by bindServer(), close(), and connectClient().
_sockfd
socket_t IpcChannel::_sockfd = INVALID_SOCKET_FD private
Definition at line 72 of file IpcChannel.hpp.
Referenced by bindServer(), close(), connectClient(), fd(), recv(), and send().
The documentation for this class was generated from the following files:
server/IpcChannel.hpp
server/IpcChannel.cpp