Mystic-Type: Network::TransportLayer::TCPSocket Class Reference
Network::TransportLayer::TCPSocket Class Reference
TCP socket wrapper providing connect/accept helpers.
#include <Network/TransportLayer/TCP/TCPSocket.hpp>
Public Member Functions
TCPSocket ()
Create a TCP socket (AF_INET / SOCK_STREAM).
~TCPSocket ()=default
bool connectTo (const std::string &ip, std::uint16_t port)
Connect to a remote TCP endpoint.
bool bindAndListen (std::uint16_t port, std::uint32_t address=INADDR_ANY, int backlog=4)
Bind to an address and start listening.
int acceptClient (struct sockaddr_in &clientAddr)
Accept an incoming client connection.
Public Member Functions inherited from Network::TransportLayer::ASocket
ASocket (int domain, int type, int protocol)
Construct a new ASocket object.
~ASocket ()
Destroy the ASocket object.
socket_t getSocketFd () const override
Get the underlying socket file descriptor.
int closeSocket () override
Close the socket.
bool bindSock (int domain, int port, uint32_t address)
Bind the socket to a specific address and port.
virtual ssize_t readByte (char *buffer, std::size_t size) override
Read bytes from the socket.
virtual ssize_t writeByte (const char *data, std::size_t size) override
Write bytes to the socket.
IOState sockState (int timeoutSec, int timeoutUsec) override
Check the socket state for read, write, or exception.
Public Member Functions inherited from Network::TransportLayer::ISocket
virtual ~ISocket ()=default
Destroy the ISocket object.
Additional Inherited Members
Protected Attributes inherited from Network::TransportLayer::ASocket
socket_t _socketFd
struct sockaddr_in _addr
Detailed Description
TCP socket wrapper providing connect/accept helpers.
Inherits the basic file descriptor management from ASocket and adds convenience methods for client connections and server listen/accept.
Definition at line 21 of file TCPSocket.hpp.
Constructor & Destructor Documentation
TCPSocket()
Network::TransportLayer::TCPSocket::TCPSocket () inline
Create a TCP socket (AF_INET / SOCK_STREAM).
Definition at line 27 of file TCPSocket.hpp.
~TCPSocket()
Network::TransportLayer::TCPSocket::~TCPSocket () default
Member Function Documentation
acceptClient()
int Network::TransportLayer::TCPSocket::acceptClient (struct sockaddr_in & clientAddr)
Accept an incoming client connection.
Parameters
clientAddr Filled with the connecting client's address.
Returns
int Accepted client socket fd, or -1 on error.
Definition at line 41 of file TCPSocket.cpp.
References Network::TransportLayer::ASocket::_socketFd.
Referenced by TCPServer::acceptNewClient().
bindAndListen()
bool Network::TransportLayer::TCPSocket::bindAndListen (std::uint16_t port, std::uint32_t address = INADDR_ANY, int backlog = 4)
Bind to an address and start listening.
Parameters
port Local port to bind.
address Local IPv4 address (default: INADDR_ANY).
backlog listen backlog size.
Returns
true on success, false otherwise.
Definition at line 27 of file TCPSocket.cpp.
References Network::TransportLayer::ASocket::_socketFd, and Network::TransportLayer::ASocket::bindSock().
Referenced by TCPServer::TCPServer().
connectTo()
bool Network::TransportLayer::TCPSocket::connectTo (const std::string & ip, std::uint16_t port)
Connect to a remote TCP endpoint.
Parameters
ip Destination IPv4 address (string form).
port Destination port.
Returns
true on success, false otherwise.
Definition at line 12 of file TCPSocket.cpp.
References Network::TransportLayer::ASocket::_socketFd.
The documentation for this class was generated from the following files:
Network/TransportLayer/TCP/TCPSocket.hpp
Network/TransportLayer/TCP/TCPSocket.cpp