Mystic-Type: Network::TransportLayer::UDPSocket Class Reference
Network::TransportLayer::UDPSocket Class Reference
UDP Socket class inheriting from ASocket.
#include <Network/TransportLayer/UDP/UDPSocket.hpp>
Public Member Functions
UDPSocket ()
Construct a new UDPSocket object.
~UDPSocket ()=default
Destroy the UDPSocket object.
ssize_t writeByte (const char *data, std::size_t size) override
Write bytes to the UDP socket.
ssize_t writeByte (const char *data, std::size_t size, const sockaddr_in &destAddr)
Write bytes to the UDP socket to a specific address.
ssize_t readByte (char *buffer, std::size_t size) override
Read bytes from the UDP socket.
sockaddr_in getSenderAddr () const
Get the sender address of the last received packet.
bool bindTo (std::uint16_t port, std::uint32_t address=INADDR_ANY)
Bind the UDP socket to a port/address.
Public Member Functions inherited from Network::TransportLayer::ASocket
ASocket (int domain, int type, int protocol)
Construct a new ASocket object.
~ASocket ()
Destroy the ASocket object.
socket_t getSocketFd () const override
Get the underlying socket file descriptor.
int closeSocket () override
Close the socket.
bool bindSock (int domain, int port, uint32_t address)
Bind the socket to a specific address and port.
IOState sockState (int timeoutSec, int timeoutUsec) override
Check the socket state for read, write, or exception.
Public Member Functions inherited from Network::TransportLayer::ISocket
virtual ~ISocket ()=default
Destroy the ISocket object.
Private Attributes
sockaddr_in _senderAddr
Additional Inherited Members
Protected Attributes inherited from Network::TransportLayer::ASocket
socket_t _socketFd
struct sockaddr_in _addr
Detailed Description
UDP Socket class inheriting from ASocket.
Definition at line 23 of file UDPSocket.hpp.
Constructor & Destructor Documentation
UDPSocket()
Network::TransportLayer::UDPSocket::UDPSocket () inline
Construct a new UDPSocket object.
Definition at line 30 of file UDPSocket.hpp.
~UDPSocket()
Network::TransportLayer::UDPSocket::~UDPSocket () default
Destroy the UDPSocket object.
Member Function Documentation
bindTo()
bool Network::TransportLayer::UDPSocket::bindTo (std::uint16_t port, std::uint32_t address = INADDR_ANY)
Bind the UDP socket to a port/address.
Parameters
port Port to bind to
address Address (default INADDR_ANY)
Returns
true on success, false otherwise
Definition at line 12 of file UDPSocket.cpp.
References Network::TransportLayer::ASocket::bindSock().
Referenced by UDPGameServer::UDPGameServer().
getSenderAddr()
sockaddr_in Network::TransportLayer::UDPSocket::getSenderAddr () const inline
Get the sender address of the last received packet.
Returns
struct sockaddr_in The sender's address
Definition at line 71 of file UDPSocket.hpp.
References _senderAddr.
Referenced by UDPGameServer::networkLoop().
readByte()
ssize_t Network::TransportLayer::UDPSocket::readByte (char * buffer, std::size_t size) override virtual
Read bytes from the UDP socket.
Parameters
buffer Buffer to store the read data
size Number of bytes to read
Returns
ssize_t Number of bytes read, or -1 on error
Reimplemented from Network::TransportLayer::ASocket.
Definition at line 35 of file UDPSocket.cpp.
References _senderAddr, Network::TransportLayer::ASocket::_socketFd, Network::TransportLayer::READ_READY, and Network::TransportLayer::ASocket::sockState().
Referenced by UDPGameServer::networkLoop().
writeByte() [1/2]
ssize_t Network::TransportLayer::UDPSocket::writeByte (const char * data, std::size_t size) override virtual
Write bytes to the UDP socket.
Parameters
data Data to write
size Number of bytes to write
Returns
ssize_t Number of bytes written, or -1 on error
Reimplemented from Network::TransportLayer::ASocket.
Definition at line 17 of file UDPSocket.cpp.
References _senderAddr, and Network::TransportLayer::ASocket::_socketFd.
Referenced by UDPGameServer::sendPacketTo().
writeByte() [2/2]
ssize_t Network::TransportLayer::UDPSocket::writeByte (const char * data, std::size_t size, const sockaddr_in & destAddr)
Write bytes to the UDP socket to a specific address.
Parameters
data Data to write
size Number of bytes to write
destAddr Destination address to send data to
Returns
ssize_t Number of bytes written, or -1 on error
Member Data Documentation
_senderAddr
sockaddr_in Network::TransportLayer::UDPSocket::_senderAddr private
Definition at line 84 of file UDPSocket.hpp.
Referenced by getSenderAddr(), readByte(), and writeByte().
The documentation for this class was generated from the following files:
Network/TransportLayer/UDP/UDPSocket.hpp
Network/TransportLayer/UDP/UDPSocket.cpp