Mystic-Type: RectangleRenderSystem Class Reference
RectangleRenderSystem Class Reference
Renders rectangle-based entities with proper coordinate transformation.
#include <graphical-client/ecs/System.hpp>
Public Member Functions
void setGameAreaOffset (float offsetX, float offsetY, float areaSize)
Sets the game area offset and size for coordinate transformation.
void update (ECS &ecs, Entity e)
Renders a rectangle entity to the screen.
Private Attributes
float _offsetX = 0.0f
float _offsetY = 0.0f
float _areaSize = 1280.0f
Detailed Description
Renders rectangle-based entities with proper coordinate transformation.
Transforms game coordinates (0-255) to screen coordinates based on game area offset and size.
Definition at line 212 of file System.hpp.
Member Function Documentation
setGameAreaOffset()
void RectangleRenderSystem::setGameAreaOffset (float offsetX, float offsetY, float areaSize) inline
Sets the game area offset and size for coordinate transformation.
Parameters
offsetX X offset of the game area on screen.
offsetY Y offset of the game area on screen.
areaSize Size of the game area in pixels.
Definition at line 221 of file System.hpp.
References _areaSize, _offsetX, and _offsetY.
Referenced by GraphicClient::init().
update()
void RectangleRenderSystem::update (ECS & ecs, Entity e) inline
Renders a rectangle entity to the screen.
Parameters
ecs Reference to the ECS system.
e The entity to render.
Definition at line 233 of file System.hpp.
References _areaSize, _offsetX, _offsetY, ECS::getComponent(), and Raylib::Draw::rectangle().
Referenced by GraphicClient::render().
Member Data Documentation
_areaSize
float RectangleRenderSystem::_areaSize = 1280.0f private
Definition at line 246 of file System.hpp.
Referenced by setGameAreaOffset(), and update().
_offsetX
float RectangleRenderSystem::_offsetX = 0.0f private
Definition at line 244 of file System.hpp.
Referenced by setGameAreaOffset(), and update().
_offsetY
float RectangleRenderSystem::_offsetY = 0.0f private
Definition at line 245 of file System.hpp.
Referenced by setGameAreaOffset(), and update().
The documentation for this class was generated from the following file:
graphical-client/ecs/System.hpp