Mystic-Type: NetworkClient Class Reference
NetworkClient Class Reference
TCP+UDP client responsible for handshake, lobby, and gameplay packets.
#include <Network/Client/NetworkClient.hpp>
Public Types
enum class MoveCmd : uint8_t { Up = 0 , Down = 1 , Left = 2 , Right = 3 }
Input directions for UDP INPUT packets.
Public Member Functions
NetworkClient (const std::string &ip, uint16_t port)
Build a client targeting a server address.
~NetworkClient ()
Disconnect on destruction.
bool connectToServer ()
Create a TCP connection and ensure UDP socket exists.
bool performHandshake ()
Perform the application handshake over TCP.
bool sendPong ()
Send TCP PONG in response to server PING.
bool sendHelloUdp (uint8_t x=0, uint8_t y=0)
Send UDP hello to register address/port on server.
bool sendInput (uint8_t posX, uint8_t posY, int8_t velX, int8_t velY, MoveCmd dir)
Send player input over UDP.
bool sendShoot (uint8_t posX, uint8_t posY, int8_t velX, int8_t velY)
Send a shoot command over UDP.
bool sendChat (const std::string &text)
Send a chat message over TCP.
bool sendCreateLobby ()
Ask the server to create a private lobby.
bool sendJoinLobby (const std::string &code)
Ask the server to join an existing lobby.
void setPseudo (const std::string &pseudo)
Set the preferred pseudo for the handshake payload.
bool sendUdpPing ()
Send a UDP ping with client timestamp.
bool pollPackets ()
Poll TCP/UDP sockets and handle any received packets.
void disconnect ()
Close TCP and UDP sockets and reset state.
void disconnectUdp ()
Close UDP socket only.
bool ensureUdp ()
Ensure UDP socket exists.
void resetForLobby ()
Reset state when entering a lobby.
void resetForReconnect ()
Reset state after a full reconnect.
bool isConnected () const
Return true when TCP is connected.
void updateServerAddress (const std::string &ip, uint16_t port)
Update remote server address for TCP and UDP.
int getPlayerId () const
Get server-assigned player id.
const std::string & getLobbyCode () const
Get current lobby code.
const std::string & getPseudo () const
Get current pseudo.
const std::vector< PlayerState > & getLastSnapshot () const
Get last received player snapshots.
const std::vector< BulletState > & getLastSnapshotBullets () const
Get last received bullet snapshots.
const std::vector< MonsterState > & getLastSnapshotMonsters () const
Get last received monster snapshots.
const std::vector< PlayerState > & getLastPlayerList () const
Get last received player list from TCP.
const std::vector< std::string > & getEvents () const
Get pending network events.
void clearEvents ()
Clear queued events.
int getUdpPingMs () const
Last measured UDP RTT in ms.
float getUdpLossPct () const
Estimated snapshot loss percentage.
float getUdpRxKbps ()
Get current UDP receive rate in Kbps.
float getUdpTxKbps ()
Get current UDP transmit rate in Kbps.
Private Types
enum class RecvResult { Disconnected , Incomplete , Ok }
Result of a framed TCP receive attempt.
Private Member Functions
bool readTcpPacket (Packet &p)
bool readUdpPacket (Packet &p)
bool sendPacketTcp (const Packet &p)
bool sendPacketUdp (const Packet &p)
void handleTcpPacket (const Packet &p)
void handleUdpPacket (const Packet &p)
bool writeAll (socket_t fd, const uint8_t *data, std::size_t size)
RecvResult receiveTcpFramed (Packet &p)
long long nowMs () const
void updateUdpRates (long long nowMs)
Private Attributes
socket_t _tcpFd = -1
socket_t _udpFd = -1
bool _tcpConnected = false
bool _udpConnected = false
sockaddr_in _tcpAddr {}
sockaddr_in _udpAddr {}
int _playerId = -1
std::string _lobbyCode
std::string _pseudo
std::vector< PlayerState > _lastSnapshot
std::vector< BulletState > _lastSnapshotBullets
std::vector< MonsterState > _lastSnapshotMonsters
std::vector< PlayerState > _lastPlayerList
std::vector< std::string > _events
std::vector< uint8_t > _tcpRecvBuffer
uint16_t _lastSnapshotSeq = 0
bool _hasSnapshotSeq = false
uint64_t _snapshotReceived = 0
uint64_t _snapshotLost = 0
int _udpPingMs = -1
uint32_t _udpLastPingSentMs = 0
uint64_t _udpBytesInWindow = 0
uint64_t _udpBytesOutWindow = 0
long long _udpRateWindowStartMs = 0
float _udpRxKbps = 0.0f
float _udpTxKbps = 0.0f
Detailed Description
TCP+UDP client responsible for handshake, lobby, and gameplay packets.
Definition at line 23 of file NetworkClient.hpp.
Member Enumeration Documentation
MoveCmd
enum class NetworkClient::MoveCmd : uint8_t strong
Input directions for UDP INPUT packets.
Enumerator
Up
Down
Left
Right
Definition at line 55 of file NetworkClient.hpp.
RecvResult
enum class NetworkClient::RecvResult strong private
Result of a framed TCP receive attempt.
Enumerator
Disconnected
Incomplete
Ok
Definition at line 175 of file NetworkClient.hpp.
Constructor & Destructor Documentation
NetworkClient()
NetworkClient::NetworkClient (const std::string & ip, uint16_t port)
Build a client targeting a server address.
Parameters
ip IPv4 address as string.
port TCP port.
Definition at line 23 of file NetworkClient.cpp.
References _tcpAddr, and _udpAddr.
~NetworkClient()
NetworkClient::~NetworkClient ()
Disconnect on destruction.
Definition at line 31 of file NetworkClient.cpp.
References disconnect().
Member Function Documentation
clearEvents()
void NetworkClient::clearEvents () inline
Clear queued events.
Definition at line 153 of file NetworkClient.hpp.
References _events.
Referenced by GraphicClient::gameLoop(), GraphicClient::init(), GraphicClient::processNetworkEvents(), and GraphicClient::selectLobby().
connectToServer()
bool NetworkClient::connectToServer ()
Create a TCP connection and ensure UDP socket exists.
Definition at line 36 of file NetworkClient.cpp.
References _tcpAddr, _tcpConnected, _tcpFd, and ensureUdp().
Referenced by GraphicClient::init().
disconnect()
void NetworkClient::disconnect ()
Close TCP and UDP sockets and reset state.
Definition at line 487 of file NetworkClient.cpp.
References _lobbyCode, _tcpConnected, _tcpFd, _udpConnected, _udpFd, and CLOSE.
Referenced by GraphicClient::gameLoop(), handleTcpPacket(), GraphicClient::processNetworkEvents(), readTcpPacket(), and ~NetworkClient().
disconnectUdp()
void NetworkClient::disconnectUdp ()
Close UDP socket only.
Definition at line 502 of file NetworkClient.cpp.
References _udpConnected, _udpFd, and CLOSE.
Referenced by GraphicClient::gameLoop(), and GraphicClient::processNetworkEvents().
ensureUdp()
bool NetworkClient::ensureUdp ()
Ensure UDP socket exists.
Definition at line 511 of file NetworkClient.cpp.
References _udpConnected, and _udpFd.
Referenced by connectToServer(), GraphicClient::init(), and resetForLobby().
getEvents()
const std::vector< std::string > & NetworkClient::getEvents () const inline
Get pending network events.
Definition at line 149 of file NetworkClient.hpp.
References _events.
Referenced by GraphicClient::gameLoop(), GraphicClient::processNetworkEvents(), and GraphicClient::selectLobby().
getLastPlayerList()
const std::vector< PlayerState > & NetworkClient::getLastPlayerList () const inline
Get last received player list from TCP.
Definition at line 145 of file NetworkClient.hpp.
References _lastPlayerList.
Referenced by GraphicClient::init(), and GraphicClient::processNetworkEvents().
getLastSnapshot()
const std::vector< PlayerState > & NetworkClient::getLastSnapshot () const inline
Get last received player snapshots.
Definition at line 133 of file NetworkClient.hpp.
References _lastSnapshot.
Referenced by GraphicClient::processNetworkEvents().
getLastSnapshotBullets()
const std::vector< BulletState > & NetworkClient::getLastSnapshotBullets () const inline
Get last received bullet snapshots.
Definition at line 137 of file NetworkClient.hpp.
References _lastSnapshotBullets.
Referenced by GraphicClient::updateEntities().
getLastSnapshotMonsters()
const std::vector< MonsterState > & NetworkClient::getLastSnapshotMonsters () const inline
Get last received monster snapshots.
Definition at line 141 of file NetworkClient.hpp.
References _lastSnapshotMonsters.
Referenced by GraphicClient::processNetworkEvents(), and GraphicClient::updateEntities().
getLobbyCode()
const std::string & NetworkClient::getLobbyCode () const inline
Get current lobby code.
Definition at line 125 of file NetworkClient.hpp.
References _lobbyCode.
Referenced by GraphicClient::render(), and GraphicClient::selectLobby().
getPlayerId()
int NetworkClient::getPlayerId () const inline
Get server-assigned player id.
Definition at line 121 of file NetworkClient.hpp.
References _playerId.
Referenced by GraphicClient::init(), GraphicClient::processNetworkEvents(), GraphicClient::render(), GraphicClient::syncEntities(), and GraphicClient::updateEntities().
getPseudo()
const std::string & NetworkClient::getPseudo () const inline
Get current pseudo.
Definition at line 129 of file NetworkClient.hpp.
References _pseudo.
getUdpLossPct()
float NetworkClient::getUdpLossPct () const
Estimated snapshot loss percentage.
Definition at line 587 of file NetworkClient.cpp.
References _snapshotLost, and _snapshotReceived.
Referenced by GraphicClient::render().
getUdpPingMs()
int NetworkClient::getUdpPingMs () const inline
Last measured UDP RTT in ms.
Definition at line 157 of file NetworkClient.hpp.
References _udpPingMs.
Referenced by GraphicClient::render().
getUdpRxKbps()
float NetworkClient::getUdpRxKbps ()
Get current UDP receive rate in Kbps.
Definition at line 595 of file NetworkClient.cpp.
References _udpRxKbps, nowMs(), and updateUdpRates().
Referenced by GraphicClient::render().
getUdpTxKbps()
float NetworkClient::getUdpTxKbps ()
Get current UDP transmit rate in Kbps.
Definition at line 601 of file NetworkClient.cpp.
References _udpTxKbps, nowMs(), and updateUdpRates().
Referenced by GraphicClient::render().
handleTcpPacket()
void NetworkClient::handleTcpPacket (const Packet & p) private
Definition at line 275 of file NetworkClient.cpp.
References _events, _lastPlayerList, _lobbyCode, _udpAddr, disconnect(), LOBBY_ERROR, LOBBY_OK, MESSAGE, NEW_PLAYER, Packet::payload, PING, PLAYER_LIST, REFUSED, sendPong(), and Packet::type.
Referenced by pollPackets().
handleUdpPacket()
void NetworkClient::handleUdpPacket (const Packet & p) private
Definition at line 347 of file NetworkClient.cpp.
References _events, _hasSnapshotSeq, _lastSnapshot, _lastSnapshotBullets, _lastSnapshotMonsters, _lastSnapshotSeq, _snapshotLost, _snapshotReceived, _udpPingMs, nowMs(), Packet::payload, PONG_UDP, SNAPSHOT, and Packet::type.
Referenced by pollPackets().
isConnected()
bool NetworkClient::isConnected () const inline
Return true when TCP is connected.
Definition at line 112 of file NetworkClient.hpp.
References _tcpConnected.
Referenced by GraphicClient::init().
nowMs()
long long NetworkClient::nowMs () const private
Definition at line 564 of file NetworkClient.cpp.
Referenced by getUdpRxKbps(), getUdpTxKbps(), handleUdpPacket(), readUdpPacket(), sendPacketUdp(), and sendUdpPing().
performHandshake()
bool NetworkClient::performHandshake ()
Perform the application handshake over TCP.
Definition at line 54 of file NetworkClient.cpp.
References _playerId, _pseudo, CLIENT_HELLO, Ok, OK, Packet::payload, receiveTcpFramed(), sendPacketTcp(), and Packet::type.
Referenced by GraphicClient::init().
pollPackets()
bool NetworkClient::pollPackets ()
Poll TCP/UDP sockets and handle any received packets.
Definition at line 232 of file NetworkClient.cpp.
References _tcpFd, _tcpRecvBuffer, _udpFd, Protocol::extractFromBuffer(), handleTcpPacket(), handleUdpPacket(), INVALID_SOCKET_FD, Protocol::Ok, readTcpPacket(), and readUdpPacket().
Referenced by GraphicClient::init(), GraphicClient::processNetworkEvents(), and GraphicClient::selectLobby().
readTcpPacket()
bool NetworkClient::readTcpPacket (Packet & p) private
Definition at line 208 of file NetworkClient.cpp.
References _events, disconnect(), Disconnected, Ok, and receiveTcpFramed().
Referenced by pollPackets().
readUdpPacket()
bool NetworkClient::readUdpPacket (Packet & p) private
Definition at line 218 of file NetworkClient.cpp.
References _udpBytesInWindow, _udpFd, BUFFER_SIZE, Packet::deserialize(), nowMs(), and updateUdpRates().
Referenced by pollPackets().
receiveTcpFramed()
NetworkClient::RecvResult NetworkClient::receiveTcpFramed (Packet & p) private
Definition at line 472 of file NetworkClient.cpp.
References _tcpFd, _tcpRecvBuffer, BUFFER_SIZE, Protocol::consumeChunk(), Disconnected, Incomplete, Protocol::Incomplete, Ok, and Protocol::Ok.
Referenced by performHandshake(), and readTcpPacket().
resetForLobby()
void NetworkClient::resetForLobby ()
Reset state when entering a lobby.
Definition at line 522 of file NetworkClient.cpp.
References _events, _hasSnapshotSeq, _lastPlayerList, _lastSnapshot, _lastSnapshotBullets, _lastSnapshotMonsters, _lobbyCode, _snapshotLost, _snapshotReceived, _tcpRecvBuffer, _udpBytesInWindow, _udpBytesOutWindow, _udpPingMs, _udpRateWindowStartMs, _udpRxKbps, _udpTxKbps, and ensureUdp().
Referenced by GraphicClient::run().
resetForReconnect()
void NetworkClient::resetForReconnect ()
Reset state after a full reconnect.
Definition at line 543 of file NetworkClient.cpp.
References _events, _hasSnapshotSeq, _lastPlayerList, _lastSnapshot, _lastSnapshotBullets, _lastSnapshotMonsters, _lobbyCode, _playerId, _snapshotLost, _snapshotReceived, _tcpRecvBuffer, _udpBytesInWindow, _udpBytesOutWindow, _udpPingMs, _udpRateWindowStartMs, _udpRxKbps, and _udpTxKbps.
sendChat()
bool NetworkClient::sendChat (const std::string & text)
Send a chat message over TCP.
Definition at line 150 of file NetworkClient.cpp.
References MESSAGE, and sendPacketTcp().
Referenced by GraphicClient::gameLoop().
sendCreateLobby()
bool NetworkClient::sendCreateLobby ()
Ask the server to create a private lobby.
Definition at line 172 of file NetworkClient.cpp.
References CREATE_LOBBY, and sendPacketTcp().
Referenced by GraphicClient::selectLobby().
sendHelloUdp()
bool NetworkClient::sendHelloUdp (uint8_t x = 0, uint8_t y = 0)
Send UDP hello to register address/port on server.
Definition at line 99 of file NetworkClient.cpp.
References _playerId, HELLO_UDP, and sendPacketUdp().
Referenced by GraphicClient::gameLoop(), and GraphicClient::init().
sendInput()
bool NetworkClient::sendInput (uint8_t posX, uint8_t posY, int8_t velX, int8_t velY, MoveCmd dir)
Send player input over UDP.
Definition at line 123 of file NetworkClient.cpp.
References _playerId, INPUT, and sendPacketUdp().
Referenced by InputSystem::update().
sendJoinLobby()
bool NetworkClient::sendJoinLobby (const std::string & code)
Ask the server to join an existing lobby.
Definition at line 179 of file NetworkClient.cpp.
References JOIN_LOBBY, and sendPacketTcp().
Referenced by GraphicClient::selectLobby().
sendPacketTcp()
bool NetworkClient::sendPacketTcp (const Packet & p) private
Definition at line 186 of file NetworkClient.cpp.
References _tcpFd, Protocol::frameTcp(), and writeAll().
Referenced by performHandshake(), sendChat(), sendCreateLobby(), sendJoinLobby(), and sendPong().
sendPacketUdp()
bool NetworkClient::sendPacketUdp (const Packet & p) private
Definition at line 197 of file NetworkClient.cpp.
References _udpAddr, _udpBytesOutWindow, _udpFd, nowMs(), Packet::serialize(), and updateUdpRates().
Referenced by sendHelloUdp(), sendInput(), sendShoot(), and sendUdpPing().
sendPong()
bool NetworkClient::sendPong ()
Send TCP PONG in response to server PING.
Definition at line 93 of file NetworkClient.cpp.
References PONG, and sendPacketTcp().
Referenced by GraphicClient::gameLoop(), handleTcpPacket(), and GraphicClient::selectLobby().
sendShoot()
bool NetworkClient::sendShoot (uint8_t posX, uint8_t posY, int8_t velX, int8_t velY)
Send a shoot command over UDP.
Definition at line 137 of file NetworkClient.cpp.
References _playerId, sendPacketUdp(), and SHOOT.
Referenced by InputSystem::update().
sendUdpPing()
bool NetworkClient::sendUdpPing ()
Send a UDP ping with client timestamp.
Definition at line 109 of file NetworkClient.cpp.
References _udpLastPingSentMs, nowMs(), PING_UDP, and sendPacketUdp().
Referenced by GraphicClient::gameLoop().
setPseudo()
void NetworkClient::setPseudo (const std::string & pseudo) inline
Set the preferred pseudo for the handshake payload.
Definition at line 79 of file NetworkClient.hpp.
References _pseudo.
Referenced by GraphicClient::selectPseudo().
updateServerAddress()
void NetworkClient::updateServerAddress (const std::string & ip, uint16_t port)
Update remote server address for TCP and UDP.
Definition at line 607 of file NetworkClient.cpp.
References _tcpAddr, and _udpAddr.
Referenced by GraphicClient::selectMainMenu().
updateUdpRates()
void NetworkClient::updateUdpRates (long long nowMs) private
Definition at line 570 of file NetworkClient.cpp.
References _udpBytesInWindow, _udpBytesOutWindow, _udpRateWindowStartMs, _udpRxKbps, and _udpTxKbps.
Referenced by getUdpRxKbps(), getUdpTxKbps(), readUdpPacket(), and sendPacketUdp().
writeAll()
bool NetworkClient::writeAll (socket_t fd, const uint8_t * data, std::size_t size) private
Definition at line 458 of file NetworkClient.cpp.
Referenced by sendPacketTcp().
Member Data Documentation
_events
std::vector<std::string> NetworkClient::_events private
Definition at line 199 of file NetworkClient.hpp.
Referenced by clearEvents(), getEvents(), handleTcpPacket(), handleUdpPacket(), readTcpPacket(), resetForLobby(), and resetForReconnect().
_hasSnapshotSeq
bool NetworkClient::_hasSnapshotSeq = false private
Definition at line 202 of file NetworkClient.hpp.
Referenced by handleUdpPacket(), resetForLobby(), and resetForReconnect().
_lastPlayerList
std::vector<PlayerState> NetworkClient::_lastPlayerList private
Definition at line 198 of file NetworkClient.hpp.
Referenced by getLastPlayerList(), handleTcpPacket(), resetForLobby(), and resetForReconnect().
_lastSnapshot
std::vector<PlayerState> NetworkClient::_lastSnapshot private
Definition at line 195 of file NetworkClient.hpp.
Referenced by getLastSnapshot(), handleUdpPacket(), resetForLobby(), and resetForReconnect().
_lastSnapshotBullets
std::vector<BulletState> NetworkClient::_lastSnapshotBullets private
Definition at line 196 of file NetworkClient.hpp.
Referenced by getLastSnapshotBullets(), handleUdpPacket(), resetForLobby(), and resetForReconnect().
_lastSnapshotMonsters
std::vector<MonsterState> NetworkClient::_lastSnapshotMonsters private
Definition at line 197 of file NetworkClient.hpp.
Referenced by getLastSnapshotMonsters(), handleUdpPacket(), resetForLobby(), and resetForReconnect().
_lastSnapshotSeq
uint16_t NetworkClient::_lastSnapshotSeq = 0 private
Definition at line 201 of file NetworkClient.hpp.
Referenced by handleUdpPacket().
_lobbyCode
std::string NetworkClient::_lobbyCode private
Definition at line 192 of file NetworkClient.hpp.
Referenced by disconnect(), getLobbyCode(), handleTcpPacket(), resetForLobby(), and resetForReconnect().
_playerId
int NetworkClient::_playerId = -1 private
Definition at line 191 of file NetworkClient.hpp.
Referenced by getPlayerId(), performHandshake(), resetForReconnect(), sendHelloUdp(), sendInput(), and sendShoot().
_pseudo
std::string NetworkClient::_pseudo private
Definition at line 193 of file NetworkClient.hpp.
Referenced by getPseudo(), performHandshake(), and setPseudo().
_snapshotLost
uint64_t NetworkClient::_snapshotLost = 0 private
Definition at line 204 of file NetworkClient.hpp.
Referenced by getUdpLossPct(), handleUdpPacket(), resetForLobby(), and resetForReconnect().
_snapshotReceived
uint64_t NetworkClient::_snapshotReceived = 0 private
Definition at line 203 of file NetworkClient.hpp.
Referenced by getUdpLossPct(), handleUdpPacket(), resetForLobby(), and resetForReconnect().
_tcpAddr
sockaddr_in NetworkClient::_tcpAddr {} private
Definition at line 189 of file NetworkClient.hpp.
Referenced by connectToServer(), NetworkClient(), and updateServerAddress().
_tcpConnected
bool NetworkClient::_tcpConnected = false private
Definition at line 187 of file NetworkClient.hpp.
Referenced by connectToServer(), disconnect(), and isConnected().
_tcpFd
socket_t NetworkClient::_tcpFd = -1 private
Definition at line 185 of file NetworkClient.hpp.
Referenced by connectToServer(), disconnect(), pollPackets(), receiveTcpFramed(), and sendPacketTcp().
_tcpRecvBuffer
std::vector<uint8_t> NetworkClient::_tcpRecvBuffer private
Definition at line 200 of file NetworkClient.hpp.
Referenced by pollPackets(), receiveTcpFramed(), resetForLobby(), and resetForReconnect().
_udpAddr
sockaddr_in NetworkClient::_udpAddr {} private
Definition at line 190 of file NetworkClient.hpp.
Referenced by handleTcpPacket(), NetworkClient(), sendPacketUdp(), and updateServerAddress().
_udpBytesInWindow
uint64_t NetworkClient::_udpBytesInWindow = 0 private
Definition at line 207 of file NetworkClient.hpp.
Referenced by readUdpPacket(), resetForLobby(), resetForReconnect(), and updateUdpRates().
_udpBytesOutWindow
uint64_t NetworkClient::_udpBytesOutWindow = 0 private
Definition at line 208 of file NetworkClient.hpp.
Referenced by resetForLobby(), resetForReconnect(), sendPacketUdp(), and updateUdpRates().
_udpConnected
bool NetworkClient::_udpConnected = false private
Definition at line 188 of file NetworkClient.hpp.
Referenced by disconnect(), disconnectUdp(), and ensureUdp().
_udpFd
socket_t NetworkClient::_udpFd = -1 private
Definition at line 186 of file NetworkClient.hpp.
Referenced by disconnect(), disconnectUdp(), ensureUdp(), pollPackets(), readUdpPacket(), and sendPacketUdp().
_udpLastPingSentMs
uint32_t NetworkClient::_udpLastPingSentMs = 0 private
Definition at line 206 of file NetworkClient.hpp.
Referenced by sendUdpPing().
_udpPingMs
int NetworkClient::_udpPingMs = -1 private
Definition at line 205 of file NetworkClient.hpp.
Referenced by getUdpPingMs(), handleUdpPacket(), resetForLobby(), and resetForReconnect().
_udpRateWindowStartMs
long long NetworkClient::_udpRateWindowStartMs = 0 private
Definition at line 209 of file NetworkClient.hpp.
Referenced by resetForLobby(), resetForReconnect(), and updateUdpRates().
_udpRxKbps
float NetworkClient::_udpRxKbps = 0.0f private
Definition at line 210 of file NetworkClient.hpp.
Referenced by getUdpRxKbps(), resetForLobby(), resetForReconnect(), and updateUdpRates().
_udpTxKbps
float NetworkClient::_udpTxKbps = 0.0f private
Definition at line 211 of file NetworkClient.hpp.
Referenced by getUdpTxKbps(), resetForLobby(), resetForReconnect(), and updateUdpRates().
The documentation for this class was generated from the following files:
Network/Client/NetworkClient.hpp
Network/Client/NetworkClient.cpp