Mystic-Type: ECS Class Reference
ECS Class Reference
Entity Component System implementation.
#include <graphical-client/ecs/Core.hpp>
Public Member Functions
ECS ()
Constructor initializing entity signatures.
Entity createEntity ()
Creates a new entity.
template<typename T >
void addComponent (Entity e, const T &c)
Adds a component to an entity.
template<typename T >
T & getComponent (Entity e)
Retrieves a component from an entity.
template<typename T >
bool hasComponent (Entity e) const
Checks if an entity has a specific component type.
template<typename T >
std::vector< T > & getAllComponents ()
Retrieves all components of a specific type.
template<typename T >
size_t getComponentTypeIndex ()
Gets the type index for a component type.
Signature getSignature (Entity e) const
Gets the signature of an entity.
Private Attributes
std::vector< Signature > signatures
std::unordered_map< std::type_index, std::unique_ptr< IComponentArray > > storages
Static Private Attributes
static size_t nextComponentIndex = 0
Detailed Description
Entity Component System implementation.
Manages entities, components, and their associations using a data-oriented architecture.
Definition at line 87 of file Core.hpp.
Constructor & Destructor Documentation
ECS()
ECS::ECS () inline
Constructor initializing entity signatures.
Definition at line 92 of file Core.hpp.
References MAX_ENTITIES, and signatures.
Member Function Documentation
addComponent()
template<typename T > void ECS::addComponent (Entity e, const T & c) inline
Adds a component to an entity.
Template Parameters
T The component type.
Parameters
e The entity ID.
c The component instance.
Definition at line 112 of file Core.hpp.
References ComponentArray< T >::add(), getComponentTypeIndex(), signatures, and storages.
Referenced by GraphicClient::createBulletEntity(), GraphicClient::createMonsterEntity(), GraphicClient::createPlayerEntity(), and GraphicClient::selectLobby().
createEntity()
Entity ECS::createEntity () inline
Creates a new entity.
Returns
The ID of the newly created entity.
Definition at line 100 of file Core.hpp.
Referenced by GraphicClient::createBulletEntity(), GraphicClient::createMonsterEntity(), GraphicClient::createPlayerEntity(), and GraphicClient::selectLobby().
getAllComponents()
template<typename T > std::vector< T > & ECS::getAllComponents () inline
Retrieves all components of a specific type.
Template Parameters
T The component type.
Returns
Reference to the vector of all components of this type.
Definition at line 155 of file Core.hpp.
References getComponentTypeIndex(), and storages.
getComponent()
template<typename T > T & ECS::getComponent (Entity e) inline
Retrieves a component from an entity.
Template Parameters
T The component type.
Parameters
e The entity ID.
Returns
Reference to the component.
Definition at line 131 of file Core.hpp.
References getComponentTypeIndex(), and storages.
Referenced by GraphicClient::selectLobby(), GraphicClient::syncBullets(), GraphicClient::syncEntities(), GraphicClient::syncMonsters(), CircleRenderSystem::update(), RectangleRenderSystem::update(), MovementSystem::update(), SpriteRenderSystem::update(), and GraphicClient::updateEntities().
getComponentTypeIndex()
template<typename T > size_t ECS::getComponentTypeIndex () inline
Gets the type index for a component type.
Template Parameters
T The component type.
Returns
Unique type index for this component.
Definition at line 165 of file Core.hpp.
References nextComponentIndex.
Referenced by addComponent(), getAllComponents(), getComponent(), getSignature(), and hasComponent().
getSignature()
Signature ECS::getSignature (Entity e) const inline
Gets the signature of an entity.
Parameters
e The entity ID.
Returns
The entity's component signature.
Definition at line 175 of file Core.hpp.
References getComponentTypeIndex(), and signatures.
hasComponent()
template<typename T > bool ECS::hasComponent (Entity e) const inline
Checks if an entity has a specific component type.
Template Parameters
T The component type.
Parameters
e The entity ID.
Returns
True if entity has component, false otherwise.
Definition at line 142 of file Core.hpp.
References getComponentTypeIndex(), and signatures.
Member Data Documentation
nextComponentIndex
size_t ECS::nextComponentIndex = 0 inline static private
Next available component type index
Definition at line 182 of file Core.hpp.
Referenced by getComponentTypeIndex().
signatures
std::vector<Signature> ECS::signatures private
Entity component signatures
Definition at line 180 of file Core.hpp.
Referenced by addComponent(), ECS(), getSignature(), and hasComponent().
storages
std::unordered_map<std::type_index, std::unique_ptr<IComponentArray> > ECS::storages private
Component storages
Definition at line 181 of file Core.hpp.
Referenced by addComponent(), getAllComponents(), and getComponent().
The documentation for this class was generated from the following file:
graphical-client/ecs/Core.hpp