Mystic-Type: SpriteRenderSystem Class Reference
SpriteRenderSystem Class Reference
Renders animated sprite entities with proper coordinate transformation.
#include <graphical-client/ecs/System.hpp>
Public Member Functions
void setScale (float sx, float sy)
Sets the sprite scaling factors.
void setGameAreaOffset (float offsetX, float offsetY, float areaSize)
Sets the game area offset and size for coordinate transformation.
void update (ECS &ecs, Entity e, float dt)
Updates and renders an animated sprite entity.
Private Attributes
float _scaleX = 1.0f
float _scaleY = 1.0f
float _offsetX = 0.0f
float _offsetY = 0.0f
float _areaSize = 1280.0f
Detailed Description
Renders animated sprite entities with proper coordinate transformation.
Handles drawing of animated sprites with scaling and converts game coordinates to screen coordinates.
Definition at line 255 of file System.hpp.
Member Function Documentation
setGameAreaOffset()
void SpriteRenderSystem::setGameAreaOffset (float offsetX, float offsetY, float areaSize) inline
Sets the game area offset and size for coordinate transformation.
Parameters
offsetX X offset of the game area on screen.
offsetY Y offset of the game area on screen.
areaSize Size of the game area in pixels.
Definition at line 271 of file System.hpp.
References _areaSize, _offsetX, and _offsetY.
Referenced by GraphicClient::init().
setScale()
void SpriteRenderSystem::setScale (float sx, float sy) inline
Sets the sprite scaling factors.
Parameters
sx Horizontal scale factor.
sy Vertical scale factor.
Definition at line 263 of file System.hpp.
References _scaleX, and _scaleY.
Referenced by GraphicClient::render().
update()
void SpriteRenderSystem::update (ECS & ecs, Entity e, float dt) inline
Updates and renders an animated sprite entity.
Parameters
ecs Reference to the ECS system.
e The entity to render.
dt Delta time since last frame for animation updates.
Definition at line 284 of file System.hpp.
References _areaSize, _offsetX, _offsetY, and ECS::getComponent().
Referenced by GraphicClient::render().
Member Data Documentation
_areaSize
float SpriteRenderSystem::_areaSize = 1280.0f private
Definition at line 304 of file System.hpp.
Referenced by setGameAreaOffset(), and update().
_offsetX
float SpriteRenderSystem::_offsetX = 0.0f private
Definition at line 302 of file System.hpp.
Referenced by setGameAreaOffset(), and update().
_offsetY
float SpriteRenderSystem::_offsetY = 0.0f private
Definition at line 303 of file System.hpp.
Referenced by setGameAreaOffset(), and update().
_scaleX
float SpriteRenderSystem::_scaleX = 1.0f private
Definition at line 300 of file System.hpp.
Referenced by setScale().
_scaleY
float SpriteRenderSystem::_scaleY = 1.0f private
Definition at line 301 of file System.hpp.
Referenced by setScale().
The documentation for this class was generated from the following file:
graphical-client/ecs/System.hpp