Mystic-Type: Raylib::Window Class Reference
Raylib::Window Class Reference
Encapsulates Raylib window management.
#include <graphical-client/Raylib/Raylib.hpp>
Public Member Functions
Window (int width, int height, const std::string &title)
Creates a Raylib window.
~Window ()
bool shouldClose () const
Checks if window should close.
void close ()
Closes the window.
void beginDrawing ()
Begins drawing frame.
void endDrawing ()
Ends drawing frame and displays it.
void clearBackground (Color color)
Clears background with specified color.
int getWidth () const
Gets window width.
int getHeight () const
Gets window height.
float getFrameTime () const
Gets time delta since last frame.
void setTargetFPS (int fps)
Sets target FPS (frames per second).
Detailed Description
Encapsulates Raylib window management.
Handles window creation, rendering, and lifecycle.
Definition at line 34 of file Raylib.hpp.
Constructor & Destructor Documentation
Window()
Raylib::Window::Window (int width, int height, const std::string & title)
Creates a Raylib window.
Parameters
width Window width in pixels.
height Window height in pixels.
title Window title string.
Definition at line 12 of file Raylib.cpp.
~Window()
Raylib::Window::~Window ()
Definition at line 16 of file Raylib.cpp.
Member Function Documentation
beginDrawing()
void Raylib::Window::beginDrawing ()
Begins drawing frame.
Definition at line 24 of file Raylib.cpp.
Referenced by GraphicClient::render(), GraphicClient::selectLobby(), GraphicClient::selectMainMenu(), GraphicClient::selectPseudo(), and GraphicClient::selectSettings().
clearBackground()
void Raylib::Window::clearBackground (Color color)
Clears background with specified color.
Parameters
color Clear color.
Definition at line 26 of file Raylib.cpp.
Referenced by GraphicClient::drawGameBackground(), GraphicClient::selectLobby(), GraphicClient::selectMainMenu(), GraphicClient::selectPseudo(), and GraphicClient::selectSettings().
close()
void Raylib::Window::close ()
Closes the window.
Definition at line 23 of file Raylib.cpp.
endDrawing()
void Raylib::Window::endDrawing ()
Ends drawing frame and displays it.
Definition at line 25 of file Raylib.cpp.
Referenced by GraphicClient::render(), GraphicClient::selectLobby(), GraphicClient::selectMainMenu(), GraphicClient::selectPseudo(), and GraphicClient::selectSettings().
getFrameTime()
float Raylib::Window::getFrameTime () const
Gets time delta since last frame.
Returns
Delta time in seconds.
Definition at line 29 of file Raylib.cpp.
Referenced by GraphicClient::gameLoop(), GraphicClient::selectLobby(), GraphicClient::selectMainMenu(), GraphicClient::selectPseudo(), and GraphicClient::selectSettings().
getHeight()
int Raylib::Window::getHeight () const
Gets window height.
Returns
Height in pixels.
Definition at line 28 of file Raylib.cpp.
getWidth()
int Raylib::Window::getWidth () const
Gets window width.
Returns
Width in pixels.
Definition at line 27 of file Raylib.cpp.
setTargetFPS()
void Raylib::Window::setTargetFPS (int fps)
Sets target FPS (frames per second).
Parameters
fps Target framerate.
Definition at line 30 of file Raylib.cpp.
Referenced by GraphicClient::GraphicClient().
shouldClose()
bool Raylib::Window::shouldClose () const
Checks if window should close.
Returns
True if close was requested, false otherwise.
Definition at line 22 of file Raylib.cpp.
Referenced by GraphicClient::gameLoop(), GraphicClient::run(), GraphicClient::selectMainMenu(), GraphicClient::selectPseudo(), and GraphicClient::selectSettings().
The documentation for this class was generated from the following files:
graphical-client/Raylib/Raylib.hpp
graphical-client/Raylib/Raylib.cpp