Mystic-Type: SessionManager Class Reference
SessionManager Class Reference
Tracks client sessions across TCP and UDP, and enforces simple rate limits.
#include <Network/SessionManager.hpp>
Public Member Functions
SessionManager (int maxInputsPerSec=30, int maxShootsPerSec=10)
Construct a manager with simple per-second rate limits.
void setOnRemove (std::function< void(int)> cb)
Set callback invoked when a session is removed.
void addSession (int id, int tcpFd, const sockaddr_in &tcpAddr, long nowMs)
Add a TCP session entry.
void removeById (int id)
Remove a session by player id.
void removeByFd (int fd)
Remove a session by TCP file descriptor.
bool setUdpAddr (int id, const sockaddr_in &udpAddr)
Register the client's UDP address.
std::optional< Session > getSession (int id) const
Lookup a session by player id.
void updatePong (int id, long nowMs)
Update last PONG time for heartbeat checks.
void setLobbyCode (int id, const std::string &code)
Store the lobby code for a player.
std::optional< std::string > getLobbyCode (int id) const
Fetch the lobby code for a player.
void setPseudo (int id, const std::string &pseudo)
Store the player's pseudo.
std::optional< std::string > getPseudo (int id) const
Fetch the player's pseudo.
bool allowInput (int id, long nowMs)
Rate-limit input packets per second.
bool allowShoot (int id, long nowMs)
Rate-limit shoot packets per second.
Private Member Functions
void resetCounter (long nowMs, long &lastMs, int &count, int limit)
Private Attributes
std::mutex _mutex
std::unordered_map< int, Session > _sessions
std::function< void(int)> _onRemove
const int _maxInputsPerSec
const int _maxShootsPerSec
Detailed Description
Tracks client sessions across TCP and UDP, and enforces simple rate limits.
Definition at line 45 of file SessionManager.hpp.
Constructor & Destructor Documentation
SessionManager()
SessionManager::SessionManager (int maxInputsPerSec = 30, int maxShootsPerSec = 10) inline
Construct a manager with simple per-second rate limits.
Definition at line 50 of file SessionManager.hpp.
Member Function Documentation
addSession()
void SessionManager::addSession (int id, int tcpFd, const sockaddr_in & tcpAddr, long nowMs)
Add a TCP session entry.
Definition at line 10 of file SessionManager.cpp.
References _mutex, _sessions, Session::id, Session::lastPong, Session::lobbyCode, Session::tcpAddr, and Session::tcpFd.
Referenced by TCPServer::acceptNewClient().
allowInput()
bool SessionManager::allowInput (int id, long nowMs)
Rate-limit input packets per second.
Definition at line 125 of file SessionManager.cpp.
References _maxInputsPerSec, _mutex, _sessions, and resetCounter().
allowShoot()
bool SessionManager::allowShoot (int id, long nowMs)
Rate-limit shoot packets per second.
Definition at line 135 of file SessionManager.cpp.
References _maxShootsPerSec, _mutex, _sessions, and resetCounter().
getLobbyCode()
std::optional< std::string > SessionManager::getLobbyCode (int id) const
Fetch the lobby code for a player.
Definition at line 88 of file SessionManager.cpp.
References _mutex, and _sessions.
Referenced by TCPServer::processClientData().
getPseudo()
std::optional< std::string > SessionManager::getPseudo (int id) const
Fetch the player's pseudo.
Definition at line 106 of file SessionManager.cpp.
References _mutex, and _sessions.
Referenced by TCPServer::processClientData().
getSession()
std::optional< Session > SessionManager::getSession (int id) const
Lookup a session by player id.
Definition at line 61 of file SessionManager.cpp.
References _mutex, and _sessions.
Referenced by UDPGameServer::handleHello(), UDPGameServer::handleInput(), and UDPGameServer::handleShoot().
removeByFd()
void SessionManager::removeByFd (int fd)
Remove a session by TCP file descriptor.
Definition at line 34 of file SessionManager.cpp.
References _mutex, _onRemove, and _sessions.
removeById()
void SessionManager::removeById (int id)
Remove a session by player id.
Definition at line 22 of file SessionManager.cpp.
References _mutex, _onRemove, and _sessions.
Referenced by TCPServer::resetClient().
resetCounter()
void SessionManager::resetCounter (long nowMs, long & lastMs, int & count, int limit) private
Definition at line 115 of file SessionManager.cpp.
Referenced by allowInput(), and allowShoot().
setLobbyCode()
void SessionManager::setLobbyCode (int id, const std::string & code)
Store the lobby code for a player.
Definition at line 79 of file SessionManager.cpp.
References _mutex, and _sessions.
Referenced by TCPServer::assignLobby(), and TCPServer::removeFromLobby().
setOnRemove()
void SessionManager::setOnRemove (std::function< void(int)> cb) inline
Set callback invoked when a session is removed.
Definition at line 56 of file SessionManager.hpp.
References _onRemove.
Referenced by UDPGameServer::UDPGameServer().
setPseudo()
void SessionManager::setPseudo (int id, const std::string & pseudo)
Store the player's pseudo.
Definition at line 97 of file SessionManager.cpp.
References _mutex, and _sessions.
Referenced by TCPServer::processClientData().
setUdpAddr()
bool SessionManager::setUdpAddr (int id, const sockaddr_in & udpAddr)
Register the client's UDP address.
Definition at line 50 of file SessionManager.cpp.
References _mutex, and _sessions.
Referenced by UDPGameServer::handleHello().
updatePong()
void SessionManager::updatePong (int id, long nowMs)
Update last PONG time for heartbeat checks.
Definition at line 70 of file SessionManager.cpp.
References _mutex, and _sessions.
Referenced by TCPServer::processClientData().
Member Data Documentation
_maxInputsPerSec
const int SessionManager::_maxInputsPerSec private
Definition at line 113 of file SessionManager.hpp.
Referenced by allowInput().
_maxShootsPerSec
const int SessionManager::_maxShootsPerSec private
Definition at line 114 of file SessionManager.hpp.
Referenced by allowShoot().
_mutex
std::mutex SessionManager::_mutex mutable private
Definition at line 110 of file SessionManager.hpp.
Referenced by addSession(), allowInput(), allowShoot(), getLobbyCode(), getPseudo(), getSession(), removeByFd(), removeById(), setLobbyCode(), setPseudo(), setUdpAddr(), and updatePong().
_onRemove
std::function<void(int)> SessionManager::_onRemove private
Definition at line 112 of file SessionManager.hpp.
Referenced by removeByFd(), removeById(), and setOnRemove().
_sessions
std::unordered_map<int, Session> SessionManager::_sessions private
Definition at line 111 of file SessionManager.hpp.
Referenced by addSession(), allowInput(), allowShoot(), getLobbyCode(), getPseudo(), getSession(), removeByFd(), removeById(), setLobbyCode(), setPseudo(), setUdpAddr(), and updatePong().
The documentation for this class was generated from the following files:
Network/SessionManager.hpp
Network/SessionManager.cpp