Mystic-Type: Raylib::Draw Class Reference
Raylib::Draw Class Reference
Static drawing utilities.
#include <graphical-client/Raylib/Raylib.hpp>
Static Public Member Functions
static void circle (int centerX, int centerY, float radius, Color color)
Draws a filled circle.
static void rectangle (int posX, int posY, int width, int height, Color color)
Draws a filled rectangle.
static void rectangleLines (int posX, int posY, int width, int height, Color color)
Draws a rectangle outline.
static void text (const std::string &msg, int posX, int posY, int fontSize, Color color)
Draws text on screen.
Detailed Description
Static drawing utilities.
Provides drawing functions for basic shapes and text.
Definition at line 150 of file Raylib.hpp.
Member Function Documentation
circle()
void Raylib::Draw::circle (int centerX, int centerY, float radius, Color color) static
Draws a filled circle.
Parameters
centerX Center X coordinate.
centerY Center Y coordinate.
radius Circle radius.
color Fill color.
Definition at line 52 of file Raylib.cpp.
Referenced by CircleRenderSystem::update().
rectangle()
void Raylib::Draw::rectangle (int posX, int posY, int width, int height, Color color) static
Draws a filled rectangle.
Parameters
posX X position.
posY Y position.
width Rectangle width.
height Rectangle height.
color Fill color.
Definition at line 57 of file Raylib.cpp.
Referenced by GraphicClient::selectLobby(), GraphicClient::selectMainMenu(), GraphicClient::selectPseudo(), GraphicClient::selectSettings(), and RectangleRenderSystem::update().
rectangleLines()
void Raylib::Draw::rectangleLines (int posX, int posY, int width, int height, Color color) static
Draws a rectangle outline.
Parameters
posX X position.
posY Y position.
width Rectangle width.
height Rectangle height.
color Outline color.
Definition at line 63 of file Raylib.cpp.
Referenced by GraphicClient::drawGameBackground(), GraphicClient::selectLobby(), GraphicClient::selectMainMenu(), GraphicClient::selectPseudo(), and GraphicClient::selectSettings().
text()
void Raylib::Draw::text (const std::string & msg, int posX, int posY, int fontSize, Color color) static
Draws text on screen.
Parameters
msg Text message.
posX X position.
posY Y position.
fontSize Font size.
color Text color.
Definition at line 68 of file Raylib.cpp.
Referenced by GraphicClient::render(), GraphicClient::selectLobby(), GraphicClient::selectMainMenu(), GraphicClient::selectPseudo(), and GraphicClient::selectSettings().
The documentation for this class was generated from the following files:
graphical-client/Raylib/Raylib.hpp
graphical-client/Raylib/Raylib.cpp