Mystic-Type: GraphicClient Class Reference
GraphicClient Class Reference
Main client application managing graphics, networking, and game state.
#include <graphical-client/GraphicClient/GraphicClient.hpp>
Public Member Functions
GraphicClient ()
Constructor initializing the graphic client.
~GraphicClient ()=default
int run ()
Main application loop.
Static Public Attributes
static constexpr float GAME_AREA_SIZE = 765.0f
static constexpr float GAME_AREA_OFFSET_X = 577.5f
static constexpr float GAME_AREA_OFFSET_Y = 157.5f
Private Member Functions
bool init ()
Initializes the client (connects to server, shows menus).
void gameLoop ()
Main game loop iteration.
void processNetworkEvents ()
Processes network events and updates game state.
void updateEntities (float dt)
Updates all game entities based on delta time.
void render (float dt)
Renders the entire game scene.
void drawGameBackground (float hoverAnimTimer)
Draws the game area background with animations.
Entity createPlayerEntity (float x, float y)
Creates a player entity at specified position.
Entity createBulletEntity (float x, float y, float vx, float vy)
Creates a bullet entity at specified position.
Entity createMonsterEntity (float x, float y, uint8_t type)
Creates a monster entity at specified position.
void syncEntities (const std::vector< PlayerState > &players)
Synchronizes player entities with server state.
void syncBullets (const std::vector< BulletState > &bullets)
Synchronizes bullet entities with server state.
void syncMonsters (const std::vector< MonsterState > &monsters)
Synchronizes monster entities with server state.
bool selectLobby ()
Shows lobby selection menu.
bool selectPseudo ()
Shows pseudo/username input menu.
bool selectMainMenu ()
Shows main menu with server connection options.
bool selectSettings ()
Shows controls settings menu for key remapping.
std::string keyboardKeyToString (KeyboardKey key)
Converts keyboard key code to human-readable string.
void disconnectAndQuit ()
Disconnects from server and quits the application.
Private Attributes
Raylib::Window _window
NetworkClient _net
GameState _state
ECS _ecs
ECS _uiEcs
SpriteRenderSystem _spriteRenderSystem
RectangleRenderSystem _rectangleRenderSystem
InputSystem _inputSystem
MovementSystem _movementSystem
std::unordered_map< int, Entity > _entities
std::unordered_map< int, Entity > _bulletEntities
std::unordered_map< int, Entity > _monsterEntities
std::vector< std::string > _chatLog
std::string _chatInput
bool _chatActive = false
std::string _localPseudo
std::string _lastChatSent
std::unordered_map< int, int > _playerPingMs
std::chrono::steady_clock::time_point _lastKeepAlive {}
std::chrono::steady_clock::time_point _lastHello {}
std::chrono::steady_clock::time_point _lastUdpPing {}
bool _udpReady = false
float _gameAnimTimer = 0.0f
bool _forceExit = false
bool _restartToMenu = false
bool _hasPseudo = false
std::string _lastInitError
std::string _serverIp = "127.0.0.1"
int _serverPort = 4243
bool _hasServerConfig = false
bool _pendingReturnToLobby = false
std::chrono::steady_clock::time_point _returnToLobbyAt {}
std::string _pendingReturnReason
Detailed Description
Main client application managing graphics, networking, and game state.
Handles game initialization, rendering, entity management, user input processing, menu interactions, and network communication with the game server.
Definition at line 27 of file GraphicClient.hpp.
Constructor & Destructor Documentation
GraphicClient()
GraphicClient::GraphicClient ()
Constructor initializing the graphic client.
Definition at line 20 of file GraphicClient.cpp.
References _lastHello, _lastKeepAlive, _window, and Raylib::Window::setTargetFPS().
~GraphicClient()
GraphicClient::~GraphicClient () default
Member Function Documentation
createBulletEntity()
Entity GraphicClient::createBulletEntity (float x, float y, float vx, float vy) private
Creates a bullet entity at specified position.
Parameters
x X position in game coordinates.
y Y position in game coordinates.
vx X velocity.
vy Y velocity.
Returns
Entity ID of created bullet.
Definition at line 94 of file GraphicClient.cpp.
References _ecs, ECS::addComponent(), and ECS::createEntity().
Referenced by syncBullets().
createMonsterEntity()
Entity GraphicClient::createMonsterEntity (float x, float y, uint8_t type) private
Creates a monster entity at specified position.
Parameters
x X position in game coordinates.
y Y position in game coordinates.
type Monster type identifier.
Returns
Entity ID of created monster.
Definition at line 103 of file GraphicClient.cpp.
References _ecs, ECS::addComponent(), and ECS::createEntity().
Referenced by syncMonsters().
createPlayerEntity()
Entity GraphicClient::createPlayerEntity (float x, float y) private
Creates a player entity at specified position.
Parameters
x X position in game coordinates.
y Y position in game coordinates.
Returns
Entity ID of created player.
Definition at line 83 of file GraphicClient.cpp.
References _ecs, ECS::addComponent(), and ECS::createEntity().
Referenced by syncEntities().
disconnectAndQuit()
void GraphicClient::disconnectAndQuit () private
Disconnects from server and quits the application.
Properly closes network connections and sets exit flag.
drawGameBackground()
void GraphicClient::drawGameBackground (float hoverAnimTimer) private
Draws the game area background with animations.
Parameters
hoverAnimTimer Animation timer for effects.
Definition at line 754 of file GraphicClient.cpp.
References _window, Raylib::Window::clearBackground(), GAME_AREA_OFFSET_X, GAME_AREA_OFFSET_Y, GAME_AREA_SIZE, and Raylib::Draw::rectangleLines().
Referenced by render().
gameLoop()
void GraphicClient::gameLoop () private
Main game loop iteration.
Definition at line 859 of file GraphicClient.cpp.
References _chatActive, _chatInput, _chatLog, _forceExit, _lastChatSent, _lastHello, _lastKeepAlive, _lastUdpPing, _localPseudo, _net, _pendingReturnReason, _pendingReturnToLobby, _restartToMenu, _returnToLobbyAt, _udpReady, _window, NetworkClient::clearEvents(), NetworkClient::disconnect(), NetworkClient::disconnectUdp(), NetworkClient::getEvents(), Raylib::Window::getFrameTime(), Raylib::Input::isKeyPressed(), processNetworkEvents(), render(), NetworkClient::sendChat(), NetworkClient::sendHelloUdp(), NetworkClient::sendPong(), NetworkClient::sendUdpPing(), Raylib::Window::shouldClose(), and updateEntities().
Referenced by run().
init()
bool GraphicClient::init () private
Initializes the client (connects to server, shows menus).
Returns
True if initialization successful, false otherwise.
Definition at line 27 of file GraphicClient.cpp.
References _hasPseudo, _hasServerConfig, _lastHello, _lastInitError, _net, _rectangleRenderSystem, _spriteRenderSystem, _state, NetworkClient::clearEvents(), NetworkClient::connectToServer(), NetworkClient::ensureUdp(), GAME_AREA_OFFSET_X, GAME_AREA_OFFSET_Y, GAME_AREA_SIZE, NetworkClient::getLastPlayerList(), NetworkClient::getPlayerId(), NetworkClient::isConnected(), GameState::listPlayers(), NetworkClient::performHandshake(), NetworkClient::pollPackets(), selectLobby(), selectMainMenu(), selectPseudo(), NetworkClient::sendHelloUdp(), RectangleRenderSystem::setGameAreaOffset(), SpriteRenderSystem::setGameAreaOffset(), syncEntities(), and GameState::upsertPlayer().
Referenced by run().
keyboardKeyToString()
std::string GraphicClient::keyboardKeyToString (KeyboardKey key) private
Converts keyboard key code to human-readable string.
Parameters
key KeyboardKey code to convert.
Returns
String representation of the key.
Definition at line 1232 of file GraphicClient.cpp.
Referenced by selectSettings().
processNetworkEvents()
void GraphicClient::processNetworkEvents () private
Processes network events and updates game state.
Definition at line 273 of file GraphicClient.cpp.
References _chatLog, _forceExit, _lastChatSent, _localPseudo, _net, _pendingReturnReason, _pendingReturnToLobby, _restartToMenu, _returnToLobbyAt, _state, _udpReady, GameState::clear(), NetworkClient::clearEvents(), GameState::clearPlayers(), NetworkClient::disconnect(), NetworkClient::disconnectUdp(), NetworkClient::getEvents(), NetworkClient::getLastPlayerList(), NetworkClient::getLastSnapshot(), NetworkClient::getLastSnapshotMonsters(), NetworkClient::getPlayerId(), GameState::listPlayers(), NetworkClient::pollPackets(), GameState::upsertMonster(), and GameState::upsertPlayer().
Referenced by gameLoop().
render()
void GraphicClient::render (float dt) private
Renders the entire game scene.
Parameters
dt Delta time since last frame.
Definition at line 774 of file GraphicClient.cpp.
References _bulletEntities, _chatActive, _chatInput, _chatLog, _ecs, _entities, _gameAnimTimer, _monsterEntities, _net, _rectangleRenderSystem, _spriteRenderSystem, _state, _window, Raylib::Window::beginDrawing(), drawGameBackground(), Raylib::Window::endDrawing(), GAME_AREA_OFFSET_X, GAME_AREA_OFFSET_Y, GAME_AREA_SIZE, NetworkClient::getLobbyCode(), NetworkClient::getPlayerId(), NetworkClient::getUdpLossPct(), NetworkClient::getUdpPingMs(), NetworkClient::getUdpRxKbps(), NetworkClient::getUdpTxKbps(), GameState::listPlayers(), SpriteRenderSystem::setScale(), Raylib::Draw::text(), RectangleRenderSystem::update(), and SpriteRenderSystem::update().
Referenced by gameLoop().
run()
int GraphicClient::run ()
Main application loop.
Returns
Exit code (0 for success).
Definition at line 973 of file GraphicClient.cpp.
References _bulletEntities, _chatActive, _chatInput, _chatLog, _entities, _forceExit, _gameAnimTimer, _lastInitError, _monsterEntities, _net, _pendingReturnReason, _pendingReturnToLobby, _playerPingMs, _restartToMenu, _state, _udpReady, _window, GameState::clear(), gameLoop(), init(), NetworkClient::resetForLobby(), and Raylib::Window::shouldClose().
Referenced by main().
selectLobby()
bool GraphicClient::selectLobby () private
Shows lobby selection menu.
Returns
True if lobby selected successfully, false otherwise.
Definition at line 416 of file GraphicClient.cpp.
References _lastKeepAlive, _net, _uiEcs, _window, ECS::addComponent(), Raylib::Window::beginDrawing(), Raylib::Window::clearBackground(), NetworkClient::clearEvents(), ECS::createEntity(), Raylib::Window::endDrawing(), ECS::getComponent(), NetworkClient::getEvents(), Raylib::Window::getFrameTime(), NetworkClient::getLobbyCode(), UIButton::hovered, Raylib::Input::isKeyPressed(), NetworkClient::pollPackets(), Raylib::Draw::rectangle(), Raylib::Draw::rectangleLines(), NetworkClient::sendCreateLobby(), NetworkClient::sendJoinLobby(), NetworkClient::sendPong(), and Raylib::Draw::text().
Referenced by init().
selectMainMenu()
bool GraphicClient::selectMainMenu () private
Shows main menu with server connection options.
Returns
True if user proceeded to game, false otherwise.
Definition at line 1007 of file GraphicClient.cpp.
References _hasServerConfig, _net, _serverIp, _serverPort, _window, Raylib::Window::beginDrawing(), Raylib::Window::clearBackground(), Raylib::Window::endDrawing(), Raylib::Window::getFrameTime(), Raylib::Input::isKeyPressed(), Raylib::Draw::rectangle(), Raylib::Draw::rectangleLines(), selectSettings(), Raylib::Window::shouldClose(), Raylib::Draw::text(), and NetworkClient::updateServerAddress().
Referenced by init().
selectPseudo()
bool GraphicClient::selectPseudo () private
Shows pseudo/username input menu.
Returns
True if pseudo entered successfully, false otherwise.
Definition at line 679 of file GraphicClient.cpp.
References _hasPseudo, _localPseudo, _net, _window, Raylib::Window::beginDrawing(), Raylib::Window::clearBackground(), Raylib::Window::endDrawing(), Raylib::Window::getFrameTime(), Raylib::Input::isKeyPressed(), Raylib::Draw::rectangle(), Raylib::Draw::rectangleLines(), NetworkClient::setPseudo(), Raylib::Window::shouldClose(), and Raylib::Draw::text().
Referenced by init().
selectSettings()
bool GraphicClient::selectSettings () private
Shows controls settings menu for key remapping.
Returns
True on menu close, false on exit.
Definition at line 1328 of file GraphicClient.cpp.
References _inputSystem, _window, Raylib::Window::beginDrawing(), Raylib::Window::clearBackground(), DOWN, Raylib::Window::endDrawing(), Raylib::Window::getFrameTime(), InputSystem::getKey(), Raylib::Input::isKeyPressed(), keyboardKeyToString(), LEFT, Raylib::Draw::rectangle(), Raylib::Draw::rectangleLines(), RIGHT, InputSystem::setKey(), SHOOT, Raylib::Window::shouldClose(), Raylib::Draw::text(), and UP.
Referenced by selectMainMenu().
syncBullets()
void GraphicClient::syncBullets (const std::vector< BulletState > & bullets) private
Synchronizes bullet entities with server state.
Parameters
bullets List of bullet states from server.
Definition at line 200 of file GraphicClient.cpp.
References _bulletEntities, _ecs, createBulletEntity(), and ECS::getComponent().
Referenced by updateEntities().
syncEntities()
void GraphicClient::syncEntities (const std::vector< PlayerState > & players) private
Synchronizes player entities with server state.
Parameters
players List of player states from server.
Definition at line 130 of file GraphicClient.cpp.
References _ecs, _entities, _net, createPlayerEntity(), ECS::getComponent(), NetworkClient::getPlayerId(), and Position::x.
Referenced by init(), and updateEntities().
syncMonsters()
void GraphicClient::syncMonsters (const std::vector< MonsterState > & monsters) private
Synchronizes monster entities with server state.
Parameters
monsters List of monster states from server.
Definition at line 239 of file GraphicClient.cpp.
References _ecs, _monsterEntities, createMonsterEntity(), ECS::getComponent(), and Position::x.
Referenced by updateEntities().
updateEntities()
void GraphicClient::updateEntities (float dt) private
Updates all game entities based on delta time.
Parameters
dt Delta time since last update.
Definition at line 371 of file GraphicClient.cpp.
References _bulletEntities, _chatActive, _ecs, _entities, _inputSystem, _movementSystem, _net, _state, ECS::getComponent(), NetworkClient::getLastSnapshotBullets(), NetworkClient::getLastSnapshotMonsters(), NetworkClient::getPlayerId(), GameState::listPlayers(), syncBullets(), syncEntities(), syncMonsters(), MovementSystem::update(), InputSystem::update(), and Position::x.
Referenced by gameLoop().
Member Data Documentation
_bulletEntities
std::unordered_map<int, Entity> GraphicClient::_bulletEntities private
Mapping of bullet IDs to entities
Definition at line 181 of file GraphicClient.hpp.
Referenced by render(), run(), syncBullets(), and updateEntities().
_chatActive
bool GraphicClient::_chatActive = false private
Chat input active flag
Definition at line 187 of file GraphicClient.hpp.
Referenced by gameLoop(), render(), run(), and updateEntities().
_chatInput
std::string GraphicClient::_chatInput private
Current chat input buffer
Definition at line 186 of file GraphicClient.hpp.
Referenced by gameLoop(), render(), and run().
_chatLog
std::vector<std::string> GraphicClient::_chatLog private
Chat message history
Definition at line 185 of file GraphicClient.hpp.
Referenced by gameLoop(), processNetworkEvents(), render(), and run().
_ecs
ECS GraphicClient::_ecs private
Main entity component system
Definition at line 171 of file GraphicClient.hpp.
Referenced by createBulletEntity(), createMonsterEntity(), createPlayerEntity(), render(), syncBullets(), syncEntities(), syncMonsters(), and updateEntities().
_entities
std::unordered_map<int, Entity> GraphicClient::_entities private
Mapping of server player IDs to entities
Definition at line 180 of file GraphicClient.hpp.
Referenced by render(), run(), syncEntities(), and updateEntities().
_forceExit
bool GraphicClient::_forceExit = false private
Force exit flag
Definition at line 202 of file GraphicClient.hpp.
Referenced by gameLoop(), processNetworkEvents(), and run().
_gameAnimTimer
float GraphicClient::_gameAnimTimer = 0.0f private
Global animation timer
Definition at line 201 of file GraphicClient.hpp.
Referenced by render(), and run().
_hasPseudo
bool GraphicClient::_hasPseudo = false private
Player has entered pseudo flag
Definition at line 204 of file GraphicClient.hpp.
Referenced by init(), and selectPseudo().
_hasServerConfig
bool GraphicClient::_hasServerConfig = false private
Server config provided flag
Definition at line 210 of file GraphicClient.hpp.
Referenced by init(), and selectMainMenu().
_inputSystem
InputSystem GraphicClient::_inputSystem private
Player input handling system
Definition at line 176 of file GraphicClient.hpp.
Referenced by selectSettings(), and updateEntities().
_lastChatSent
std::string GraphicClient::_lastChatSent private
Last sent chat message
Definition at line 191 of file GraphicClient.hpp.
Referenced by gameLoop(), and processNetworkEvents().
_lastHello
std::chrono::steady_clock::time_point GraphicClient::_lastHello {} private
Last hello packet time
Definition at line 196 of file GraphicClient.hpp.
Referenced by gameLoop(), GraphicClient(), and init().
_lastInitError
std::string GraphicClient::_lastInitError private
Last initialization error message
Definition at line 205 of file GraphicClient.hpp.
Referenced by init(), and run().
_lastKeepAlive
std::chrono::steady_clock::time_point GraphicClient::_lastKeepAlive {} private
Last keep-alive packet time
Definition at line 195 of file GraphicClient.hpp.
Referenced by gameLoop(), GraphicClient(), and selectLobby().
_lastUdpPing
std::chrono::steady_clock::time_point GraphicClient::_lastUdpPing {} private
Last UDP ping time
Definition at line 197 of file GraphicClient.hpp.
Referenced by gameLoop().
_localPseudo
std::string GraphicClient::_localPseudo private
Local player username
Definition at line 190 of file GraphicClient.hpp.
Referenced by gameLoop(), processNetworkEvents(), and selectPseudo().
_monsterEntities
std::unordered_map<int, Entity> GraphicClient::_monsterEntities private
Mapping of monster IDs to entities
Definition at line 182 of file GraphicClient.hpp.
Referenced by render(), run(), and syncMonsters().
_movementSystem
MovementSystem GraphicClient::_movementSystem private
Entity movement system
Definition at line 177 of file GraphicClient.hpp.
Referenced by updateEntities().
_net
NetworkClient GraphicClient::_net private
Network client for server communication
Definition at line 167 of file GraphicClient.hpp.
Referenced by gameLoop(), init(), processNetworkEvents(), render(), run(), selectLobby(), selectMainMenu(), selectPseudo(), syncEntities(), and updateEntities().
_pendingReturnReason
std::string GraphicClient::_pendingReturnReason private
Reason for returning to lobby
Definition at line 215 of file GraphicClient.hpp.
Referenced by gameLoop(), processNetworkEvents(), and run().
_pendingReturnToLobby
bool GraphicClient::_pendingReturnToLobby = false private
Pending return to lobby flag
Definition at line 213 of file GraphicClient.hpp.
Referenced by gameLoop(), processNetworkEvents(), and run().
_playerPingMs
std::unordered_map<int, int> GraphicClient::_playerPingMs private
Ping values for each player
Definition at line 194 of file GraphicClient.hpp.
Referenced by run().
_rectangleRenderSystem
RectangleRenderSystem GraphicClient::_rectangleRenderSystem private
Rectangle rendering system
Definition at line 175 of file GraphicClient.hpp.
Referenced by init(), and render().
_restartToMenu
bool GraphicClient::_restartToMenu = false private
Restart to menu flag
Definition at line 203 of file GraphicClient.hpp.
Referenced by gameLoop(), processNetworkEvents(), and run().
_returnToLobbyAt
std::chrono::steady_clock::time_point GraphicClient::_returnToLobbyAt {} private
Time to return to lobby
Definition at line 214 of file GraphicClient.hpp.
Referenced by gameLoop(), and processNetworkEvents().
_serverIp
std::string GraphicClient::_serverIp = "127.0.0.1" private
Server IP address
Definition at line 208 of file GraphicClient.hpp.
Referenced by selectMainMenu().
_serverPort
int GraphicClient::_serverPort = 4243 private
Server port number
Definition at line 209 of file GraphicClient.hpp.
Referenced by selectMainMenu().
_spriteRenderSystem
SpriteRenderSystem GraphicClient::_spriteRenderSystem private
Sprite rendering system
Definition at line 174 of file GraphicClient.hpp.
Referenced by init(), and render().
_state
GameState GraphicClient::_state private
Current game state from server
Definition at line 168 of file GraphicClient.hpp.
Referenced by init(), processNetworkEvents(), render(), run(), and updateEntities().
_udpReady
bool GraphicClient::_udpReady = false private
UDP connection ready flag
Definition at line 198 of file GraphicClient.hpp.
Referenced by gameLoop(), processNetworkEvents(), and run().
_uiEcs
ECS GraphicClient::_uiEcs private
UI entity component system
Definition at line 172 of file GraphicClient.hpp.
Referenced by selectLobby().
_window
Raylib::Window GraphicClient::_window private
Game window handle
Definition at line 164 of file GraphicClient.hpp.
Referenced by drawGameBackground(), gameLoop(), GraphicClient(), render(), run(), selectLobby(), selectMainMenu(), selectPseudo(), and selectSettings().
GAME_AREA_OFFSET_X
constexpr float GraphicClient::GAME_AREA_OFFSET_X = 577.5f static constexpr
Game area X offset on screen
Definition at line 42 of file GraphicClient.hpp.
Referenced by drawGameBackground(), init(), and render().
GAME_AREA_OFFSET_Y
constexpr float GraphicClient::GAME_AREA_OFFSET_Y = 157.5f static constexpr
Game area Y offset on screen
Definition at line 43 of file GraphicClient.hpp.
Referenced by drawGameBackground(), init(), and render().
GAME_AREA_SIZE
constexpr float GraphicClient::GAME_AREA_SIZE = 765.0f static constexpr
Game area render size in pixels
Definition at line 41 of file GraphicClient.hpp.
Referenced by drawGameBackground(), init(), and render().
The documentation for this class was generated from the following files:
graphical-client/GraphicClient/GraphicClient.hpp
graphical-client/GraphicClient/GraphicClient.cpp