Mystic-Type: Network::TransportLayer::ASocket Class Reference
Network::TransportLayer::ASocket Class Reference
#include <Network/TransportLayer/ASocket.hpp>
Public Member Functions
ASocket (int domain, int type, int protocol)
Construct a new ASocket object.
~ASocket ()
Destroy the ASocket object.
socket_t getSocketFd () const override
Get the underlying socket file descriptor.
int closeSocket () override
Close the socket.
bool bindSock (int domain, int port, uint32_t address)
Bind the socket to a specific address and port.
virtual ssize_t readByte (char *buffer, std::size_t size) override
Read bytes from the socket.
virtual ssize_t writeByte (const char *data, std::size_t size) override
Write bytes to the socket.
IOState sockState (int timeoutSec, int timeoutUsec) override
Check the socket state for read, write, or exception.
Public Member Functions inherited from Network::TransportLayer::ISocket
virtual ~ISocket ()=default
Destroy the ISocket object.
Protected Attributes
socket_t _socketFd
struct sockaddr_in _addr
Detailed Description
Definition at line 14 of file ASocket.hpp.
Constructor & Destructor Documentation
ASocket()
Network::TransportLayer::ASocket::ASocket (int domain, int type, int protocol)
Construct a new ASocket object.
Parameters
domain The communication domain (e.g., AF_INET)
type The communication type (e.g., SOCK_STREAM)
protocol The protocol to be used (e.g., IPPROTO_TCP)
Definition at line 14 of file ASocket.cpp.
References _socketFd, and INVALID_SOCKET_FD.
~ASocket()
Network::TransportLayer::ASocket::~ASocket ()
Destroy the ASocket object.
Definition at line 23 of file ASocket.cpp.
References closeSocket().
Member Function Documentation
bindSock()
bool Network::TransportLayer::ASocket::bindSock (int domain, int port, uint32_t address)
Bind the socket to a specific address and port.
Parameters
domain The communication domain (e.g., AF_INET)
port The port number to bind to
address The IP address to bind to (in network byte order)
Returns
true if binding is successful, false otherwise
Definition at line 78 of file ASocket.cpp.
References _addr, and _socketFd.
Referenced by Network::TransportLayer::TCPSocket::bindAndListen(), and Network::TransportLayer::UDPSocket::bindTo().
closeSocket()
int Network::TransportLayer::ASocket::closeSocket () override virtual
Close the socket.
Implements Network::TransportLayer::ISocket.
Definition at line 28 of file ASocket.cpp.
References _socketFd, CLOSE, and INVALID_SOCKET_FD.
Referenced by ~ASocket(), and TCPServer::~TCPServer().
getSocketFd()
socket_t Network::TransportLayer::ASocket::getSocketFd () const inline override virtual
Get the underlying socket file descriptor.
Returns
int The socket file descriptor
Implements Network::TransportLayer::ISocket.
Definition at line 37 of file ASocket.hpp.
References _socketFd.
Referenced by TCPServer::run().
readByte()
ssize_t Network::TransportLayer::ASocket::readByte (char * buffer, std::size_t size) override virtual
Read bytes from the socket.
Parameters
buffer Buffer to store the read data
size Number of bytes to read
Returns
ssize_t Number of bytes read, or -1 on error
Implements Network::TransportLayer::ISocket.
Reimplemented in Network::TransportLayer::UDPSocket.
Definition at line 96 of file ASocket.cpp.
References _socketFd, Network::TransportLayer::READ_READY, and sockState().
sockState()
IOState Network::TransportLayer::ASocket::sockState (int timeoutSec, int timeoutUsec) override virtual
Check the socket state for read, write, or exception.
Parameters
timeoutSec Timeout in seconds
timeoutUsec Timeout in microseconds
Returns
IOState The state of the socket
Implements Network::TransportLayer::ISocket.
Definition at line 39 of file ASocket.cpp.
References _socketFd, Network::TransportLayer::EXCEPTION, Network::TransportLayer::IOERROR, Network::TransportLayer::READ_READY, Network::TransportLayer::TIMEOUT, and Network::TransportLayer::WRITE_READY.
Referenced by readByte(), Network::TransportLayer::UDPSocket::readByte(), and writeByte().
writeByte()
ssize_t Network::TransportLayer::ASocket::writeByte (const char * data, std::size_t size) override virtual
Write bytes to the socket.
Parameters
data Data to write
size Number of bytes to write
Returns
ssize_t Number of bytes written, or -1 on error
Implements Network::TransportLayer::ISocket.
Reimplemented in Network::TransportLayer::UDPSocket.
Definition at line 87 of file ASocket.cpp.
References _socketFd, sockState(), and Network::TransportLayer::WRITE_READY.
Member Data Documentation
_addr
struct sockaddr_in Network::TransportLayer::ASocket::_addr protected
Definition at line 87 of file ASocket.hpp.
Referenced by bindSock().
_socketFd
socket_t Network::TransportLayer::ASocket::_socketFd protected
Definition at line 86 of file ASocket.hpp.
Referenced by Network::TransportLayer::TCPSocket::acceptClient(), ASocket(), Network::TransportLayer::TCPSocket::bindAndListen(), bindSock(), closeSocket(), Network::TransportLayer::TCPSocket::connectTo(), getSocketFd(), readByte(), Network::TransportLayer::UDPSocket::readByte(), sockState(), writeByte(), and Network::TransportLayer::UDPSocket::writeByte().
The documentation for this class was generated from the following files:
Network/TransportLayer/ASocket.hpp
Network/TransportLayer/ASocket.cpp