Mystic-Type: UDPGameServer Class Reference
UDPGameServer Class Reference
Simple UDP authoritative game server that manages players and snapshots.
#include <Network/TransportLayer/UDP/UDPGameServer.hpp>
Classes
struct Incoming
Public Member Functions
UDPGameServer (uint16_t port, SessionManager &sessions, long long snapshotIntervalMs=500, std::string lobbyCode="PUBLIC")
~UDPGameServer ()
void run ()
Start the main server loop (blocking).
void setIpc (IpcChannel *ipc)
Private Member Functions
void handlePacket (const Packet &packet, const sockaddr_in &from)
Route an incoming packet to the appropriate handler.
void handleHello (const Packet &packet, const sockaddr_in &from)
Register a new player on receipt of a hello message.
void handleInput (const Packet &packet, const sockaddr_in &from)
Update player inputs (movement/direction).
void handleShoot (const Packet &packet)
Handle a shoot command (spawn a bullet).
void broadcastSnapshot ()
Broadcast the current snapshot to all connected players.
bool sendPacketTo (const Packet &packet, const sockaddr_in &to)
Send a packet to a single endpoint.
long long nowMs () const
Monotonic time helper in milliseconds.
void updateSimulation (long long nowMs, long long deltaMs)
Advance the local simulation based on elapsed time.
void networkLoop ()
Thread loop to read incoming UDP packets without blocking the simulation tick.
std::string logPrefix () const
Private Attributes
Network::TransportLayer::UDPSocket _socket
std::unordered_map< std::string, GameWorld > _worlds
std::unordered_map< int, std::string > _playerLobby
SessionManager & _sessions
long long _lastSnapshotMs = 0
long long _lastTickMs = 0
const uint16_t _port
const long long _snapshotIntervalMs
std::string _expectedLobby
const long long _tickIntervalMs = 32
std::queue< Incoming > _incoming
std::mutex _queueMutex
std::atomic< bool > _running {false}
std::thread _networkThread
IpcChannel * _ipc = nullptr
Detailed Description
Simple UDP authoritative game server that manages players and snapshots.
The server listens on a UDP port, accepts player "hello" packets, tracks their positions/velocities, updates a small simulation loop, and periodically broadcasts snapshots to all connected players.
Definition at line 32 of file UDPGameServer.hpp.
Constructor & Destructor Documentation
UDPGameServer()
UDPGameServer::UDPGameServer (uint16_t port, SessionManager & sessions, long long snapshotIntervalMs = 500, std::string lobbyCode = "PUBLIC") explicit
Definition at line 18 of file UDPGameServer.cpp.
References _expectedLobby, _playerLobby, _sessions, _socket, _worlds, Network::TransportLayer::UDPSocket::bindTo(), logPrefix(), GameWorld::setLogPrefix(), and SessionManager::setOnRemove().
~UDPGameServer()
UDPGameServer::~UDPGameServer ()
Definition at line 45 of file UDPGameServer.cpp.
References _networkThread, and _running.
Member Function Documentation
broadcastSnapshot()
void UDPGameServer::broadcastSnapshot () private
Broadcast the current snapshot to all connected players.
Definition at line 65 of file UDPGameServer.cpp.
References _worlds, and sendPacketTo().
Referenced by run().
handleHello()
void UDPGameServer::handleHello (const Packet & packet, const sockaddr_in & from) private
Register a new player on receipt of a hello message.
Parameters
packet Incoming hello packet.
from Sender endpoint.
Definition at line 75 of file UDPGameServer.cpp.
References _expectedLobby, _playerLobby, _sessions, _worlds, GameWorld::buildSnapshotPacket(), SessionManager::getSession(), logPrefix(), Packet::payload, GameWorld::registerPlayer(), sendPacketTo(), GameWorld::setLogPrefix(), and SessionManager::setUdpAddr().
Referenced by handlePacket().
handleInput()
void UDPGameServer::handleInput (const Packet & packet, const sockaddr_in & from) private
Update player inputs (movement/direction).
Parameters
packet Incoming input packet.
from Sender endpoint.
Definition at line 103 of file UDPGameServer.cpp.
References _expectedLobby, _playerLobby, _sessions, _worlds, SessionManager::getSession(), logPrefix(), and Packet::payload.
Referenced by handlePacket().
handlePacket()
void UDPGameServer::handlePacket (const Packet & packet, const sockaddr_in & from) private
Route an incoming packet to the appropriate handler.
Parameters
packet Parsed packet contents.
from Sender endpoint.
Definition at line 174 of file UDPGameServer.cpp.
References handleHello(), handleInput(), handleShoot(), HELLO_UDP, INPUT, Packet::payload, PING_UDP, PONG_UDP, sendPacketTo(), SHOOT, and Packet::type.
Referenced by run().
handleShoot()
void UDPGameServer::handleShoot (const Packet & packet) private
Handle a shoot command (spawn a bullet).
Definition at line 140 of file UDPGameServer.cpp.
References _expectedLobby, _playerLobby, _sessions, _worlds, SessionManager::getSession(), and Packet::payload.
Referenced by handlePacket().
logPrefix()
std::string UDPGameServer::logPrefix () const private
Definition at line 299 of file UDPGameServer.cpp.
References _expectedLobby, and _port.
Referenced by handleHello(), handleInput(), networkLoop(), and UDPGameServer().
networkLoop()
void UDPGameServer::networkLoop () private
Thread loop to read incoming UDP packets without blocking the simulation tick.
Definition at line 277 of file UDPGameServer.cpp.
References _incoming, _queueMutex, _running, _socket, Packet::deserialize(), UDPGameServer::Incoming::from, Network::TransportLayer::UDPSocket::getSenderAddr(), logPrefix(), UDPGameServer::Incoming::pkt, and Network::TransportLayer::UDPSocket::readByte().
Referenced by run().
nowMs()
long long UDPGameServer::nowMs () const private
Monotonic time helper in milliseconds.
Definition at line 53 of file UDPGameServer.cpp.
Referenced by run(), and updateSimulation().
run()
void UDPGameServer::run ()
Start the main server loop (blocking).
Definition at line 195 of file UDPGameServer.cpp.
References _incoming, _ipc, _lastSnapshotMs, _lastTickMs, _networkThread, _queueMutex, _running, _snapshotIntervalMs, _tickIntervalMs, broadcastSnapshot(), handlePacket(), networkLoop(), nowMs(), IpcChannel::send(), and updateSimulation().
Referenced by main().
sendPacketTo()
bool UDPGameServer::sendPacketTo (const Packet & packet, const sockaddr_in & to) private
Send a packet to a single endpoint.
Parameters
packet Packet to send.
to Destination endpoint.
Returns
true on success, false otherwise.
Definition at line 59 of file UDPGameServer.cpp.
References _socket, Packet::serialize(), and Network::TransportLayer::UDPSocket::writeByte().
Referenced by broadcastSnapshot(), handleHello(), and handlePacket().
setIpc()
void UDPGameServer::setIpc (IpcChannel * ipc) inline
Definition at line 41 of file UDPGameServer.hpp.
References _ipc.
Referenced by main().
updateSimulation()
void UDPGameServer::updateSimulation (long long nowMs, long long deltaMs) private
Advance the local simulation based on elapsed time.
Parameters
nowMs Current timestamp in milliseconds.
Definition at line 234 of file UDPGameServer.cpp.
References _expectedLobby, _ipc, _playerLobby, _running, _worlds, nowMs(), and IpcChannel::send().
Referenced by run().
Member Data Documentation
_expectedLobby
std::string UDPGameServer::_expectedLobby private
Definition at line 113 of file UDPGameServer.hpp.
Referenced by handleHello(), handleInput(), handleShoot(), logPrefix(), UDPGameServer(), and updateSimulation().
_incoming
std::queue<Incoming> UDPGameServer::_incoming private
Definition at line 119 of file UDPGameServer.hpp.
Referenced by networkLoop(), and run().
_ipc
IpcChannel* UDPGameServer::_ipc = nullptr private
Definition at line 123 of file UDPGameServer.hpp.
Referenced by run(), setIpc(), and updateSimulation().
_lastSnapshotMs
long long UDPGameServer::_lastSnapshotMs = 0 private
Definition at line 109 of file UDPGameServer.hpp.
Referenced by run().
_lastTickMs
long long UDPGameServer::_lastTickMs = 0 private
Definition at line 110 of file UDPGameServer.hpp.
Referenced by run().
_networkThread
std::thread UDPGameServer::_networkThread private
Definition at line 122 of file UDPGameServer.hpp.
Referenced by run(), and ~UDPGameServer().
_playerLobby
std::unordered_map<int, std::string> UDPGameServer::_playerLobby private
Definition at line 107 of file UDPGameServer.hpp.
Referenced by handleHello(), handleInput(), handleShoot(), UDPGameServer(), and updateSimulation().
_port
const uint16_t UDPGameServer::_port private
Definition at line 111 of file UDPGameServer.hpp.
Referenced by logPrefix().
_queueMutex
std::mutex UDPGameServer::_queueMutex private
Definition at line 120 of file UDPGameServer.hpp.
Referenced by networkLoop(), and run().
_running
std::atomic<bool> UDPGameServer::_running {false} private
Definition at line 121 of file UDPGameServer.hpp.
Referenced by networkLoop(), run(), updateSimulation(), and ~UDPGameServer().
_sessions
SessionManager& UDPGameServer::_sessions private
Definition at line 108 of file UDPGameServer.hpp.
Referenced by handleHello(), handleInput(), handleShoot(), and UDPGameServer().
_snapshotIntervalMs
const long long UDPGameServer::_snapshotIntervalMs private
Definition at line 112 of file UDPGameServer.hpp.
Referenced by run().
_socket
Network::TransportLayer::UDPSocket UDPGameServer::_socket private
Definition at line 105 of file UDPGameServer.hpp.
Referenced by networkLoop(), sendPacketTo(), and UDPGameServer().
_tickIntervalMs
const long long UDPGameServer::_tickIntervalMs = 32 private
Definition at line 114 of file UDPGameServer.hpp.
Referenced by run().
_worlds
std::unordered_map<std::string, GameWorld> UDPGameServer::_worlds private
Definition at line 106 of file UDPGameServer.hpp.
Referenced by broadcastSnapshot(), handleHello(), handleInput(), handleShoot(), UDPGameServer(), and updateSimulation().
The documentation for this class was generated from the following files:
Network/TransportLayer/UDP/UDPGameServer.hpp
Network/TransportLayer/UDP/UDPGameServer.cpp