Mystic-Type: InputSystem Class Reference
InputSystem Class Reference
Handles player input and keyboard key binding management.
#include <graphical-client/ecs/System.hpp>
Public Member Functions
InputSystem ()
Constructor initializing default key bindings.
void setKey (KeyEvent event, KeyboardKey key)
Sets a custom key binding for a specific action.
KeyboardKey getKey (KeyEvent event) const
Retrieves the current key binding for an action.
void update (NetworkClient &net, const Position &pos, Velocity &vel)
Updates input state and sends player commands to the server.
Private Attributes
NetworkClient::MoveCmd _lastDir = NetworkClient::MoveCmd::Right
std::unordered_map< uint8_t, KeyboardKey > _keyMap
Detailed Description
Handles player input and keyboard key binding management.
This system manages keyboard input, detects key presses/holds, and communicates player movement and shooting commands to the server. Players can configure custom key bindings for all actions.
Definition at line 41 of file System.hpp.
Constructor & Destructor Documentation
InputSystem()
InputSystem::InputSystem () inline
Constructor initializing default key bindings.
Sets up default arrow keys for movement and A for shooting.
Definition at line 50 of file System.hpp.
References _keyMap, DOWN, LEFT, RIGHT, SHOOT, and UP.
Member Function Documentation
getKey()
KeyboardKey InputSystem::getKey (KeyEvent event) const inline
Retrieves the current key binding for an action.
Parameters
event The KeyEvent action to query.
Returns
The KeyboardKey currently bound to this action.
Definition at line 74 of file System.hpp.
References _keyMap.
Referenced by GraphicClient::selectSettings().
setKey()
void InputSystem::setKey (KeyEvent event, KeyboardKey key) inline
Sets a custom key binding for a specific action.
Parameters
event The KeyEvent action to rebind.
key The KeyboardKey to bind to this action.
Definition at line 64 of file System.hpp.
References _keyMap.
Referenced by GraphicClient::selectSettings().
update()
void InputSystem::update (NetworkClient & net, const Position & pos, Velocity & vel) inline
Updates input state and sends player commands to the server.
Processes keyboard input for movement and shooting, applies velocity changes, and sends commands to the server for validation and propagation to other players.
Parameters
net Reference to NetworkClient for sending commands to server.
pos Current player position.
vel Reference to velocity component (modified by this method).
Definition at line 90 of file System.hpp.
References _keyMap, _lastDir, DOWN, NetworkClient::Down, Raylib::Input::isKeyDown(), Raylib::Input::isKeyPressed(), LEFT, NetworkClient::Left, RIGHT, NetworkClient::Right, NetworkClient::sendInput(), NetworkClient::sendShoot(), SHOOT, UP, NetworkClient::Up, Velocity::vx, Velocity::vy, Position::x, and Position::y.
Referenced by GraphicClient::updateEntities().
Member Data Documentation
_keyMap
std::unordered_map<uint8_t, KeyboardKey> InputSystem::_keyMap private
Definition at line 145 of file System.hpp.
Referenced by getKey(), InputSystem(), setKey(), and update().
_lastDir
NetworkClient::MoveCmd InputSystem::_lastDir = NetworkClient::MoveCmd::Right private
Definition at line 144 of file System.hpp.
Referenced by update().
The documentation for this class was generated from the following file:
graphical-client/ecs/System.hpp