Mystic-Type: Raylib::Input Class Reference
Raylib::Input Class Reference
Static input handling utilities.
#include <graphical-client/Raylib/Raylib.hpp>
Static Public Member Functions
static bool isKeyDown (int key)
Checks if a key is currently pressed down.
static bool isKeyPressed (int key)
Checks if a key was just pressed this frame.
Detailed Description
Static input handling utilities.
Provides keyboard input detection functions.
Definition at line 198 of file Raylib.hpp.
Member Function Documentation
isKeyDown()
bool Raylib::Input::isKeyDown (int key) static
Checks if a key is currently pressed down.
Parameters
key Raylib key code.
Returns
True if key is held down, false otherwise.
Definition at line 73 of file Raylib.cpp.
Referenced by InputSystem::update().
isKeyPressed()
bool Raylib::Input::isKeyPressed (int key) static
Checks if a key was just pressed this frame.
Parameters
key Raylib key code.
Returns
True if key was just pressed, false otherwise.
Definition at line 74 of file Raylib.cpp.
Referenced by GraphicClient::gameLoop(), GraphicClient::selectLobby(), GraphicClient::selectMainMenu(), GraphicClient::selectPseudo(), GraphicClient::selectSettings(), and InputSystem::update().
The documentation for this class was generated from the following files:
graphical-client/Raylib/Raylib.hpp
graphical-client/Raylib/Raylib.cpp