Mystic-Type: /home/loic/EPITECH/rtype/Mystic-Type/game.cpp File Reference
/home/loic/EPITECH/rtype/Mystic-Type/game.cpp File Reference
#include "src/Network/TransportLayer/UDP/UDPGameServer.hpp"
#include "src/Network/SessionManager.hpp"
#include "src/server/IpcChannel.hpp"
#include <iostream>
#include <string>
#include <optional>
#include <cstdlib>
#include <sstream>
#include <thread>
Functions
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 50 of file game.cpp.
References IpcChannel::connectClient(), UDPGameServer::run(), IpcChannel::send(), and UDPGameServer::setIpc().