Mystic-Type: Protocol Namespace Reference
Protocol Namespace Reference
Enumerations
enum class StreamStatus { Disconnected , Incomplete , Ok }
Status for framed TCP stream parsing.
Functions
std::vector< uint8_t > frameTcp (const Packet &packet)
Build a TCP framed buffer (2 bytes length + serialized packet).
StreamStatus extractFromBuffer (std::vector< uint8_t > &recvBuffer, Packet &out)
Try to extract a complete packet from an accumulated stream buffer.
StreamStatus consumeChunk (const uint8_t *data, std::size_t len, std::vector< uint8_t > &recvBuffer, Packet &out)
Append newly read bytes then attempt extraction.
Enumeration Type Documentation
StreamStatus
enum class Protocol::StreamStatus strong
Status for framed TCP stream parsing.
Enumerator
Disconnected
Incomplete
Ok
Definition at line 19 of file Protocol.hpp.
Function Documentation
consumeChunk()
Protocol::StreamStatus Protocol::consumeChunk (const uint8_t * data, std::size_t len, std::vector< uint8_t > & recvBuffer, Packet & out)
Append newly read bytes then attempt extraction.
Definition at line 46 of file Protocol.cpp.
References extractFromBuffer().
Referenced by TCPServer::receivePacket(), and NetworkClient::receiveTcpFramed().
extractFromBuffer()
Protocol::StreamStatus Protocol::extractFromBuffer (std::vector< uint8_t > & recvBuffer, Packet & out)
Try to extract a complete packet from an accumulated stream buffer.
Parameters
recvBuffer Mutable buffer that stores previous bytes.
out Parsed packet on success.
Returns
StreamStatus
Definition at line 26 of file Protocol.cpp.
References Packet::deserialize().
Referenced by consumeChunk(), and NetworkClient::pollPackets().
frameTcp()
std::vector< uint8_t > Protocol::frameTcp (const Packet & packet)
Build a TCP framed buffer (2 bytes length + serialized packet).
Exceptions
std::runtime_error if payload is too large.
Definition at line 11 of file Protocol.cpp.
References Packet::serialize().
Referenced by TCPServer::sendPacket(), and NetworkClient::sendPacketTcp().