Mystic-Type Graphical Client: IScene Class Reference
IScene Class Reference abstract
Abstract base interface for all scene implementations.
#include <IScene.hpp>
Public Member Functions
virtual ~IScene ()=default
Virtual destructor.
virtual void onEnter ()=0
Called when the scene becomes the active scene.
virtual void onExit ()=0
Called when the scene is being deactivated.
virtual void update (float dt)=0
Updates the scene logic.
virtual void render (float dt)=0
Renders the scene.
virtual void setSceneManager (SceneManager *sceneManager)
Sets the scene manager reference (optional)
Detailed Description
Abstract base interface for all scene implementations.
Defines the interface that all scenes must implement to work with the SceneManager. A scene represents a distinct state or screen in the game, such as menu, lobby, gameplay, or end screen.
Note
All derived classes must implement the pure virtual methods.
Definition at line 24 of file IScene.hpp.
Member Function Documentation
onEnter()
virtual void IScene::onEnter () pure virtual
Called when the scene becomes the active scene.
Use this method to initialize scene-specific resources, such as loading assets, setting up entities, or initializing state.
Implemented in GameScene, LobbyScene, and MenuScene.
Referenced by SceneManager::changeScene().
onExit()
virtual void IScene::onExit () pure virtual
Called when the scene is being deactivated.
Use this method to clean up resources and save any necessary state before transitioning to another scene.
Implemented in GameScene, LobbyScene, and MenuScene.
Referenced by SceneManager::changeScene().
render()
virtual void IScene::render (float dt) pure virtual
Renders the scene.
Called every frame to render all visual elements of the scene. This should include drawing backgrounds, entities, UI elements, etc.
Parameters
dt Delta time since the last frame (in seconds)
Implemented in GameScene, LobbyScene, and MenuScene.
Referenced by SceneManager::render().
setSceneManager()
virtual void IScene::setSceneManager (SceneManager * sceneManager) inline virtual
Sets the scene manager reference (optional)
Called by SceneManager to provide a reference to itself. This allows scenes to transition to other scenes.
Parameters
sceneManager Pointer to the SceneManager instance
Note
Only override this if your scene needs to change scenes. The default implementation does nothing.
Reimplemented in GameScene, LobbyScene, and MenuScene.
Definition at line 78 of file IScene.hpp.
update()
virtual void IScene::update (float dt) pure virtual
Updates the scene logic.
Called every frame to update game logic, handle input, process network events, and update entity states.
Parameters
dt Delta time since the last frame (in seconds)
Implemented in GameScene, LobbyScene, and MenuScene.
Referenced by SceneManager::update().
The documentation for this class was generated from the following file:
src/graphical-client/Scenes/IScene.hpp