Mystic-Type Graphical Client: SceneManager Class Reference
SceneManager Class Reference
Manages scene lifecycle and transitions.
#include <SceneManager.hpp>
Public Member Functions
SceneManager ()
Constructs a SceneManager instance.
~SceneManager ()=default
Destructor.
void registerScene (const std::string &name, std::shared_ptr< IScene > scene)
Registers a scene with a unique identifier.
bool changeScene (const std::string &name)
Transitions to a different scene.
void update (float dt)
Updates the current active scene.
void render (float dt)
Renders the current active scene.
IScene * getCurrentScene () const
Gets the currently active scene.
Detailed Description
Manages scene lifecycle and transitions.
The SceneManager is responsible for:
Registering scenes with unique string identifiers
Transitioning between scenes with proper lifecycle callbacks
Updating and rendering the active scene each frame
Usage example:
SceneManager manager;
auto gameScene = std::make_shared<GameScene>(window, net);
manager.registerScene("game", gameScene);
manager.changeScene("game");
// In game loop:
manager.update(deltaTime);
manager.render(deltaTime);
Definition at line 36 of file SceneManager.hpp.
Constructor & Destructor Documentation
SceneManager()
SceneManager::SceneManager () inline
Constructs a SceneManager instance.
Initializes with no active scene.
Definition at line 43 of file SceneManager.hpp.
Member Function Documentation
changeScene()
bool SceneManager::changeScene (const std::string & name)
Transitions to a different scene.
Calls onExit() on the current scene (if any) and onEnter() on the new scene.
Parameters
name Identifier of the scene to transition to
Returns
true if the transition was successful, false if the scene doesn't exist
Definition at line 15 of file SceneManager.cpp.
References IScene::onEnter(), and IScene::onExit().
Referenced by MenuScene::update().
getCurrentScene()
IScene * SceneManager::getCurrentScene () const inline
Gets the currently active scene.
Returns
Pointer to the current scene, or nullptr if no scene is active
Definition at line 93 of file SceneManager.hpp.
registerScene()
void SceneManager::registerScene (const std::string & name, std::shared_ptr< IScene > scene)
Registers a scene with a unique identifier.
Parameters
name Unique string identifier for the scene
scene Shared pointer to the scene implementation
Note
If a scene with the same name already exists, it will be replaced.
Definition at line 10 of file SceneManager.cpp.
render()
void SceneManager::render (float dt)
Renders the current active scene.
Parameters
dt Delta time since the last frame (in seconds)
Note
Does nothing if no scene is currently active.
Definition at line 41 of file SceneManager.cpp.
References IScene::render().
update()
void SceneManager::update (float dt)
Updates the current active scene.
Parameters
dt Delta time since the last frame (in seconds)
Note
Does nothing if no scene is currently active.
Definition at line 34 of file SceneManager.cpp.
References IScene::update().
The documentation for this class was generated from the following files:
src/graphical-client/Scenes/SceneManager.hpp
src/graphical-client/Scenes/SceneManager.cpp